---
title: "Case Study 1: HeLa Cell Cycling"
author: 
- name:  "Antoine Bodein"
  affiliation: "CHU de Québec Research Center, Université Laval, Molecular Medicine department, Québec, QC, Canada"
  email: "antoine.bodein.1@ulaval.ca"
output: 
  BiocStyle::html_document
  

bibliography: ["mybib.bib"]
biblio-style: apalike
link-citations: true
---


```{r, echo = F}
knitr::opts_chunk$set(cache = TRUE, message = FALSE, warning = FALSE)
dir.create("./figure")
dir.create("./result")
```

```{r, message=FALSE}
library(tidyverse)
library(mixOmics)
library(timeOmics)
library(igraph)
library(minet)
library(gprofiler2)
library(RandomWalkRestartMH)
library(GO.db)
library(ComplexHeatmap)
library(org.Hs.eg.db)
```

```{r, cache=FALSE}
source("./CS1_utils.R")
```

# Preprocessing

```{r preprocessing_1}
all_data <- openxlsx::read.xlsx("data/pgen.1005554.s012.xlsx", startRow = 2)

conv <- AnnotationDbi::select(org.Hs.eg.db, keytype = "UNIPROT", keys = all_data$Leading.Uniprot.IDs, 
               columns = c("SYMBOL")) %>% 
    unique %>% na.omit
# from uniprot retriver
conv <- read_tsv("./data/uniprot_mapping.tab") %>% unique

type <- c("Translation.(LFQ)", "Translation.(iBAQ)", "Protein.(iBAQ)", "Protein.(LFQ)", "mRNA")
DATA <- purrr::map(type, ~{all_data %>% dplyr::select(Leading.Uniprot.IDs, contains(.x))}) %>%
    purrr::map(~ .x %>% as_tibble %>% column_to_rownames("Leading.Uniprot.IDs") %>% t %>% as.data.frame(stringsAsFactor = FALSE))
names(DATA) <- type


lapply(DATA, dim)

lapply(DATA, rownames)
DATA <- lapply(DATA, function(x) `rownames<-`(x,rownames(x) %>% str_remove(".*\\.")))

mRNA <- DATA$mRNA %>% t %>% as.data.frame %>% na.omit() %>% t %>% as.data.frame()
trans <- lapply(DATA$`Translation.(iBAQ)`, function(x) as.character(x) %>% as.numeric) %>% as.data.frame(row.names =  rownames(DATA$`Translation.(iBAQ)`)) %>%  t %>% as.data.frame %>% na.omit() %>% t %>% as.data.frame()
protein <- lapply(DATA$`Protein.(iBAQ)`, function(x) as.character(x) %>% as.numeric) %>% as.data.frame(row.names =  rownames(DATA$`Protein.(iBAQ)`)) %>%  t %>% as.data.frame %>% na.omit() %>% t %>% as.data.frame()

all(rownames(mRNA) == rownames(trans))
all(rownames(mRNA) == rownames(protein))


hist(t(mRNA))  # RMA = background correction + log2 transform
hist(t(trans))
hist(t(protein))

tmp_data = list("mRNA" = mRNA, "Translation" = trans, "Protein" = protein) %>%
imap_dfr( ~{
    .x %>% rownames_to_column("sample") %>% 
        gather(molecule, value, -sample) %>%
        mutate(Omics = .y)
})
ggplot(tmp_data, aes(x=value, fill=Omics)) +
    geom_histogram(binwidth=.2, alpha=.5, position="identity")+
    scale_fill_manual(values = mixOmics::color.mixo(1:3)) +
    theme_bw() +
    ggtitle("Platform-specific dynamic range") + xlab("Expression") + ylab("Counts")

save(mRNA, trans, protein, file = "./norm_data.rda")
```

```{r preprocessing_2}
mRNA.fc <- remove.fold.change(mRNA, log(2),hist.title = "mRNA FC log 2", plot = TRUE)
mRNA.fc <- mRNA.fc %>% rownames_to_column("sample") %>% gather(molecule, value, -sample) %>%
    left_join(conv, by = c("molecule"="UNIPROT")) %>% na.omit %>%
    dplyr::select(sample, SYMBOL, value) %>%
    group_by(sample, SYMBOL) %>%
    summarise(value = mean(value)) %>%
    spread(SYMBOL, value) %>%
    column_to_rownames("sample")

trans.fc <- remove.fold.change(trans, log(3),hist.title = "trans FC log 2", plot = TRUE)
trans.fc <- trans.fc %>% rownames_to_column("sample") %>% gather(molecule, value, -sample) %>%
    filter(molecule %in% conv$UNIPROT) %>% 
    dplyr::select(sample, molecule, value) %>% spread(molecule, value) %>%
    column_to_rownames("sample")

prot.fc <- remove.fold.change(protein, log(3),hist.title = "prot FC log 2", plot = TRUE)
prot.fc <- prot.fc %>% rownames_to_column("sample") %>% gather(molecule, value, -sample) %>%
    filter(molecule %in% conv$UNIPROT) %>% 
    dplyr::select(sample, molecule, value) %>% spread(molecule, value) %>%
column_to_rownames("sample")

colnames(mRNA.fc) <- paste0("mRNA_", colnames(mRNA.fc))
colnames(trans.fc) <- paste0("trans_", colnames(trans.fc))
colnames(prot.fc) <- paste0("prot_", colnames(prot.fc))

# modelling
# median value
mRNA.fc %>% rownames_to_column("sample") %>% mutate(group = sample %>% str_remove("_.*")) %>%
    gather(feature, value, -c(sample, group)) %>% 
    group_by(group, feature) %>%
    summarise(Value = median(value)) %>%
#    summarise(Value = mean(value)) %>%
    spread(feature, Value) %>%
    as.data.frame() %>%
    column_to_rownames("group") -> mRNA.modelled
mRNA.modelled <- mRNA.modelled[c("G1", "S", "G2/M"),]
    
    
trans.fc %>% rownames_to_column("sample") %>% mutate(group = sample %>% str_remove("_.*")) %>%
    gather(feature, value, -c(sample, group)) %>% 
    group_by(group, feature) %>%
    summarise(Value = median(value)) %>%
#    summarise(Value = mean(value)) %>%
    spread(feature, Value) %>%
    as.data.frame() %>%
    column_to_rownames("group") -> trans.modelled
trans.modelled <- trans.modelled[c("G1", "S", "G2/M"),]


prot.fc %>% rownames_to_column("sample") %>% mutate(group = sample %>% str_remove("_.*")) %>%
    gather(feature, value, -c(sample, group)) %>% 
    group_by(group, feature) %>%
    summarise(Value = median(value)) %>%
#    summarise(Value = mean(value)) %>%
    spread(feature, Value) %>%
    as.data.frame() %>%
    column_to_rownames("group") -> prot.modelled
prot.modelled <- prot.modelled[c("G1", "S", "G2/M"),]


save(mRNA.fc, prot.fc, trans.fc, mRNA.modelled, trans.modelled, prot.modelled, file = "./modelled_data.rda")
```

# Modelling
```{r modelling_1}
time <- rownames(mRNA.fc) %>% str_remove("_.*") %>% factor(levels = c("G1","S","G2/M")) %>% as.numeric

lmms.output <- lmms::lmmSpline(data = mRNA.fc, time = time,
                               sampleID = rownames(mRNA.fc), deri = FALSE,
                               basis = "cubic p-spline", numCores = 4, timePredict = 1:3, 
                               keepModels = TRUE)
modelled.data <- t(slot(lmms.output, 'predSpline'))

lmms.mRNA <- wrapper.lmms(mRNA.fc, time, sampleID = rownames(mRNA.fc))
lmms.mRNA$summary
mRNA.filter <- lmms.filter.lines(data = mRNA.fc, 
                                lmms.obj = lmms.mRNA$pspline, time = time) %>% .$filtered

lmms.trans <- wrapper.lmms(trans.fc, time, sampleID = rownames(trans.fc))
lmms.trans$summary
trans.filter <- lmms.filter.lines(data = trans.fc, 
                                 lmms.obj = lmms.trans$pspline, time = time) %>% .$filtered

lmms.prot <- wrapper.lmms(prot.fc, time, sampleID = rownames(prot.fc))
lmms.prot$summary
prot.filter <- lmms.filter.lines(data = prot.fc, 
                                  lmms.obj = lmms.prot$pspline, time = time) %>% .$filtered

# remove from fc 
mRNA.fc <- dplyr::select(mRNA.fc, colnames(mRNA.filter))
trans.fc <- dplyr::select(trans.fc, colnames(trans.filter))
prot.fc <- dplyr::select(prot.fc, colnames(prot.filter))

save(mRNA.fc, prot.fc, trans.fc, mRNA.filter, trans.filter, prot.filter, file = "./data_filtered.rda")
```

# Clustering
```{r timeOmics_1}
data.mean <- list("mRNA" = mRNA.modelled, "trans" = trans.modelled, "prot"=prot.modelled)

cb.modelled <- do.call("cbind", data.mean)
colnames(cb.modelled) <- lapply(data.mean, colnames) %>% unlist

block.res <- block.pls(data.mean, ncomp = 1, indY = 1, scale = FALSE, mode = "canonical")
quick_silhouette(cb.modelled, getCluster(block.res))

block.res <- block.pls(data.mean, ncomp = 3, indY = 1, scale = FALSE, mode = "canonical")
quick_silhouette(cb.modelled, getCluster(block.res))

block.res <- block.pls(data.mean, ncomp = 2, indY = 1, scale = FALSE, mode = "canonical")
quick_silhouette(cb.modelled, getCluster(block.res))

plotLong(block.res, time = c(1,2,3), legend = TRUE)

cluster.info <- getCluster(block.res)
summary_cluster(cluster.info)


# cb.modelled %>% t %>% as.data.frame() %>% rownames_to_column("molecule") %>% 
#     left_join(cluster.info)

to.cluster.info.modelled <- getCluster(block.res)
cluster_homo_block(to.cluster.info.modelled)
summary_cluster(to.cluster.info.modelled)
quick_silhouette(cb.modelled, to.cluster.info.modelled)

#2 filtered data
data.lmms <- list("mRNA" = mRNA.filter, "trans" = trans.filter, "prot"=prot.filter)
lapply(data.lmms, dim)
cb.lmms <- do.call("cbind", data.lmms)
colnames(cb.lmms) <- lapply(data.lmms, colnames) %>% unlist

block.res <- block.pls(data.lmms, ncomp = 2, indY = 1, scale = FALSE, mode = "canonical")
plotLong(block.res, legend = TRUE)

block.res <- block.pls(data.lmms, ncomp = 3, indY = 1, scale = FALSE, mode = "canonical")
quick_silhouette(cb.lmms, getCluster(block.res))


to.cluster.info.lmms <- getCluster(block.res)
cluster_homo_block(to.cluster.info.lmms)
summary_cluster(to.cluster.info.lmms)
quick_silhouette(cb.lmms, to.cluster.info.lmms)


   
######################################################
# cluster up/down
######################################################

up_down_cluster <- function(x){
    lapply(x, function(x) diff(x) %>% 
               sign %>% 
               paste(collapse = "_")) %>% 
        as.data.frame(check.names = FALSE) %>%
        t %>% as.data.frame(check.names = FALSE) %>%
        rownames_to_column("molecule") %>%
        dplyr::rename(cluster = V1) %>%
        #  pull(cluster) -> zz
        # mutate(cluster = str_split(cluster, "_")) %>%
         # pull(cluster) -> zz
        mutate(cluster = sign_to_updown(cluster))
}

sign_to_updown <- function(zz){
    r <- vector(mode = "character", length = length(zz))
    for(i in 1:length(zz)){
      # print(z)
        z = zz[i] %>% str_split( "_") %>% unlist()
        r[i] <- data.frame("val" = z) %>% mutate(conv = ifelse(val == 1, "Up", ifelse(val == -1, "Down", "0"))) %>%
            pull(conv) %>% paste(collapse = "_")
    }
    return(r)
}
    
#1. modelled 
cluster.info.updown.mean <- imap_dfr(data.mean, ~{up_down_cluster(.x) %>% mutate(block = .y)})

# plot
cb.modelled %>% scale %>% as.data.frame() %>% rownames_to_column("time") %>% gather(molecule, value, -time) %>%
    left_join(cluster.info.updown.mean) %>%
    mutate(time = factor(time, levels = c("G1","S", "G2/M")) %>% as.numeric()) %>%
    ggplot(aes(x = time, y = value, group =  molecule, col = block)) + 
    geom_line() +
    facet_wrap(~cluster)


cluster_homo_block(cluster.info.updown.mean)
summary_cluster(cluster.info.updown.mean)
quick_silhouette(cb.modelled, cluster.info.updown.mean)

#2. lmms
cluster.info.updown.lmms <- imap_dfr(data.lmms, ~{up_down_cluster(.x) %>% mutate(block = .y)})

# plot
png("./figure/CS1_clusters.png", height =  1500, width = 3000, res = 300)
cb.lmms %>% scale %>% as.data.frame() %>% rownames_to_column("time") %>% gather(molecule, value, -time) %>%
  left_join(cluster.info.updown.lmms) %>% 
  # mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Down", "Up_Up", "Down_Down"))) %>%
  mutate(cluster = case_when(
    cluster == "Down_Up" ~ "Cluster 1", 
    cluster == "Up_Up" ~ "Cluster 2",
    cluster == "Down_Down" ~ "Cluster 3",
    cluster == "Up_Down" ~ "Cluster 4",
  )) %>%
  mutate(block = case_when(
    block == "mRNA" ~ "mRNA", 
    block == "trans" ~ "Translation products", 
    block == "prot" ~ "Proteins", 
  ) %>% factor(., levels = c("mRNA", "Translation products", "Proteins"))) %>% 
  mutate( Omics = block) %>%
  mutate(time = time %>% as.numeric()) %>%
  ggplot(aes(x = time, y = value, group =  molecule, col = Omics)) + 
  geom_line() +
  facet_wrap(~cluster, nrow = 2) + scale_color_manual(values = color.mixo(1:3)) +
  theme_bw() +
  #theme(legend.position = "bottom") +
  scale_x_continuous(breaks = c(1,2,3), labels = c("G1", "S", "G2/M")) +
  ggtitle("HeLa cell clycling data clusters, scale = TRUE") + xlab("Time") + ylab("Scaled expression value")
dev.off()

cluster_homo_block(cluster.info.updown.lmms)
summary_cluster(cluster.info.updown.lmms) %>% rowSums(.)
quick_silhouette(cb.lmms, cluster.info.updown.lmms)

cluster.info <- cluster.info.updown.lmms
tmp <- summary_cluster(cluster.info.updown.lmms) %>% cbind(max = rowSums(., na.rm = TRUE)) %>% arrange(desc(max)) %>%
  dplyr::select(mRNA, trans, prot)
tmp[is.na(tmp)] <- 0
# in %
map2(tmp, colSums(tmp),~.x/.y) %>% as.data.frame() %>% `row.names<-`(rownames(tmp))
rowSums(tmp)
save(cluster.info, file = "./luster_info.rda")
```

# Gene graph

```{r grn_1}
mim <- minet::build.mim(mRNA.fc)
GRN.adg <- aracne(mim)

GRN <- graph_from_adjacency_matrix(GRN.adg, mode = "undirected")
plot(GRN, vertex.label = NA, vertex.size = 4)

GRN.cluster <- cluster.info %>% filter(block == "mRNA") %>% split(.$cluster) %>%
    lapply(function(x) dplyr::select(mRNA.fc, intersect(colnames(mRNA.fc), x$molecule)) %>%
               minet::build.mim() %>% aracne %>%
               graph_from_adjacency_matrix(mode = "undirected"))

par(mfrow = c(2,2))
imap(GRN.cluster, ~{
  plot(.x, main = .y,vertex.label = NA, vertex.size = 4, vertex.color = "lightblue")
})
par(mfrow = c(1,1))

get_stats_graph(GRN) %>% as.data.frame() %>% mutate(cluster = "all")
imap_dfr(GRN.cluster, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))

GRN.cluster[["all"]] = GRN
imap_dfr(GRN.cluster, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y)) %>% 
  mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
  arrange(cluster)

for(i in names(GRN.cluster)){
    vertex_attr(graph = GRN.cluster[[i]])$name <- vertex_attr(graph = GRN.cluster[[i]])$name %>%
        str_remove("mRNA_")
    vertex_attr(graph = GRN.cluster[[i]])$type <- rep("Gene", length(vertex_attr(graph = GRN.cluster[[i]])$name)) 
}

save(GRN.cluster, file = "./GRN.rda")
```

# prot graph

```{r prot_graph_1, eval=FALSE}
# Proteins BIOGRID
biogrid <- read_tsv("data/BIOGRID-ALL-3.5.187.tab3.txt")
biogrid.filtered <- biogrid %>% dplyr::select("Official Symbol Interactor A", "Official Symbol Interactor B") %>% unique %>%
    set_names(c("A", "B"))

#write_csv(x = as.data.frame(c(biogrid.filtered$A, biogrid.filtered$B) %>% unique), path = "./paper/uniprot_biogrid_mapping.csv", col_names = FALSE)
# use of annotationDbi
conv.biogrid <- AnnotationDbi::select(org.Hs.eg.db, keytype = "SYMBOL", keys = c(biogrid.filtered$A, biogrid.filtered$B), 
                   columns = c("UNIPROT")) %>%
    unique %>% na.omit

biogrid.filtered <- biogrid.filtered %>% left_join(conv.biogrid, by = c("A"="SYMBOL")) %>% dplyr::rename(A.UNIPROT = UNIPROT) %>%
    left_join(conv.biogrid, by = c("B"="SYMBOL")) %>% dplyr::rename(B.UNIPROT = UNIPROT) %>%
    dplyr::select(A.UNIPROT, B.UNIPROT) %>%
    na.omit() %>% unique
save(biogrid.filtered, file = "data/BIOGRID.rda")
  ```

```{r, cache=TRUE}
load("data/BIOGRID.rda")
```


```{r prot_graph_2}
BIOGRID <- graph_from_data_frame(biogrid.filtered, directed = FALSE) %>% simplify()

prot.nodes.df <- conv %>% filter(UNIPROT %in% str_remove(colnames(prot.modelled), "prot_")) %>% 
    filter(UNIPROT %in% V(BIOGRID)$name) 
prot.nodes <- prot.nodes.df %>% pull("UNIPROT")

PPI_EGO <- biogrid.filtered %>% filter(A.UNIPROT %in% prot.nodes | B.UNIPROT %in% prot.nodes) %>%
       graph_from_data_frame(directed = FALSE) %>% simplify()
PPI_EGO <- subgraph(BIOGRID, v = V(PPI_EGO)$name)
vcount(PPI_EGO)

PPI <- subgraph(BIOGRID, v = prot.nodes[prot.nodes %in% V(BIOGRID)$name])

```

```{r prot_graph_3}
prot.cluster <- cluster.info %>% filter(block == "prot") %>% 
    mutate(molecule = molecule %>% str_remove(".*_")) %>%
    left_join(conv, by = c("molecule"="UNIPROT")) %>%
    split(.$cluster)
PPI_cluster <- lapply(prot.cluster, function(x){
    # subgraph(PPI,intersect(V(PPI)$name, x$SYMBOL))
    subgraph(PPI,intersect(V(PPI)$name, x$molecule))
})
PPI_cluster[["all"]] <-  subgraph(PPI, v = intersect(lapply(prot.cluster, function(x) x$molecule) %>% unlist(), V(PPI)$name))

imap_dfr(PPI_cluster, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y)}) %>%
    dplyr::select(name, cluster) %>% 
    #unique %>%
    group_by(cluster) %>%
    summarise(N = n()) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")

# stats
imap_dfr(PPI_cluster, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y)) %>% 
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster)

detach("package:igraph", unload=TRUE)
library(igraph)
PPI_cluster.ego <- lapply(prot.cluster, function(x){
    make_ego_graph(PPI_EGO, order = 1, 
                  # nodes = intersect(V(PPI)$name, x$SYMBOL)) %>%
                  nodes = intersect(V(PPI)$name, x$molecule)) %>%
    
        do.call(what = "union")
})
PPI_cluster.ego[["all"]] <- PPI_EGO

imap_dfr(PPI_cluster.ego, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))%>% 
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster)

imap_dfr(PPI_cluster.ego, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y) %>%
        mutate(type = ifelse(name %in% (do.call("rbind", prot.cluster) %>% filter(cluster == .y)  %>% pull(molecule)), "prot", "ego"))}) %>%
    dplyr::select(name, cluster, type) %>%
    #unique %>%
    group_by(cluster, type) %>%
    summarise(N = n()) %>%
    spread(type, N) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")
```

```{r tfome, eval=FALSE}
TFome <- read_tsv("~/work/WORK:analysis/human_tf2DNA/TF2DNA_exp_uniq.txt", col_names = F)
names(TFome) <- c("TF","Target")

TFome2 <- read_tsv("~/Documents/TO2/LOREAL/Data/Proteomic/trrust_rawdata.human.tsv", col_names = F)
colnames(TFome2) <- c("TF", "Target", "Regulation", 'PMID')
TFome2 <- TFome2[,c(1,2)]

TFome <- rbind(TFome, TFome2) %>% unique

TFome %>% dim

conv.ego <- AnnotationDbi::select(org.Hs.eg.db, keytype = "UNIPROT", keys = V(PPI_EGO)$name, 
                           columns = c("SYMBOL")) %>%
    unique %>% na.omit

# use TF(uniprot) -> Target(Symbol)
TFome.filtered <- TFome %>% left_join(conv.ego, by = c("TF"="SYMBOL")) %>% na.omit %>%
    dplyr::rename("TF.uniprot" = "UNIPROT") %>%
    dplyr::select(TF.uniprot, Target) %>% # UNIPROT -> SYMBOL
    unique %>%
    set_names(c("Prot", "Gene")) %>%
    mutate(from = Prot, to = Gene)
    # mutate(interaction_type = "TF")

coding.filtered <- conv.ego %>% set_names(c("Prot", "Gene")) %>%
    mutate(from = Gene, to = Prot)
    #%>%
    #mutate(interaction_type = "coding")

link_gene_prot = rbind(TFome.filtered, coding.filtered) #%>% graph_from_data_frame(directed = FALSE)

merge_GRN_PPI <- function(GRN, PPI, interaction.df){
    # filter interaction
    if(is.null(GRN)){
        return(PPI)
    }
    if(is.null(PPI)){
        return(GRN)
    }
    interaction.graph <- interaction.df %>% 
        filter(Gene %in% V(GRN)$name, Prot %in% V(PPI)$name) %>%
        dplyr::select(from,to) %>%
        graph_from_data_frame(directed = FALSE)
    
    tmp <- igraph::union(GRN, interaction.graph)
    GRN_PPI <- igraph::union(tmp, PPI)
    return(GRN_PPI)
}

GRN_PPI <- list()
GRN_PPI.ego <- list()
for(i in names(GRN.cluster)){
    print(i)
    GRN_PPI[[i]] <- merge_GRN_PPI(GRN = GRN.cluster[[i]], 
                                 PPI = PPI_cluster[[i]], 
                                 interaction.df = link_gene_prot)
    GRN_PPI.ego[[i]] <- merge_GRN_PPI(GRN = GRN.cluster[[i]], 
                                  PPI = PPI_cluster.ego[[i]], 
                                  interaction.df = link_gene_prot)
    
}

save(GRN_PPI, GRN_PPI.ego, PPI_cluster.ego, PPI_cluster, file = "./result/GRN_PPI.rda")
```

```{r}
load("./result/GRN_PPI.rda")
```

```{r tfome2}
imap_dfr(PPI_cluster, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))
imap_dfr(PPI_cluster.ego, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))
imap_dfr(GRN_PPI, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))
imap_dfr(GRN_PPI.ego, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y))

# stats
# TF -> genes
TFome.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    unique %>% nrow
TFome.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    pull(Prot) %>% unique %>% length
TFome.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    pull(Gene) %>% unique %>% length

# genes -> protein coding
coding.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    unique %>% nrow
coding.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    pull(Prot) %>% unique %>% length
coding.filtered %>% filter((Prot %in% V(PPI_cluster$all)$name) & (Gene %in% V(GRN.cluster$all)$name)) %>%
    pull(Gene) %>% unique %>% length

par(mfrow = c(2,2))
imap(PPI_cluster[1:3], ~{
    remove.isolated.nodes(.x, simplify = TRUE) %>%
    plot(main = .y,vertex.label = NA, vertex.size = 4, vertex.color = "orange")
})
par(mfrow = c(1,1))

imap_dfr(GRN_PPI.ego, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y)}) %>%
    dplyr::select(type, name, cluster) %>% 
    #unique %>%
    group_by(type, cluster) %>%
    summarise(N = n()) %>% spread(type, N) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")
```

# ORA
```{r ora1}
load(".//luster_info.rda")
load(".//GRN_PPI.rda")


list.conv <- cluster.info %>% filter(block %in% c("prot", "trans")) %>% pull(molecule) %>% str_remove('trans_') %>% str_remove("prot_") %>% unique()
conv.tab <- AnnotationDbi::select(org.Hs.eg.db, keytype = "UNIPROT", keys = list.conv, 
                                  columns = c("SYMBOL")) %>%
    unique %>% na.omit

# gene
cluster.mRNA <- cluster.info %>% filter(block == "mRNA") %>% mutate(molecule = molecule %>% str_remove("mRNA_")) %>%
    split(.$cluster)
enrich.mRNA <- lapply(cluster.mRNA, function(x) gprofiler2::gost(query = x$molecule, organism = "hsapiens", significant = FALSE))
enrich.mRNA[["all"]] <- gprofiler2::gost(query = (cluster.mRNA %>% lapply(function(x)x$molecule) %>% unlist %>% unname), organism = "hsapiens", significant = FALSE)
#openxlsx::write.xlsx(x = purrr::map(enrich.mRNA, ~.x$result), file = "./analysis/enrich_mRNA.xlsx")

# prot
cluster.prot <- cluster.info %>% filter(block == "prot") %>% mutate(molecule = molecule %>% str_remove("prot_")) %>%
    left_join(conv.tab, by = c("molecule"="UNIPROT")) %>% 
    split(.$cluster)
enrich.prot <- lapply(cluster.prot, function(x) gprofiler2::gost(query = x$SYMBOL, organism = "hsapiens", significant = FALSE))
enrich.prot[["all"]] <- gprofiler2::gost(query = (cluster.prot %>% lapply(function(x)x$SYMBOL) %>% unlist %>% unname), organism = "hsapiens", significant = FALSE)
#openxlsx::write.xlsx(x = purrr::map(enrich.prot, ~.x$result), file = "./analysis/enrich_prot.xlsx")


#trans
cluster.trans <- cluster.info %>% filter(block == "trans") %>% mutate(molecule = molecule %>% str_remove("trans_")) %>%
    left_join(conv.tab, by = c("molecule"="UNIPROT")) %>% 
    split(.$cluster)
enrich.trans <- lapply(cluster.prot, function(x) gprofiler2::gost(query = x$SYMBOL, organism = "hsapiens", significant = FALSE))
enrich.trans[["all"]] <- gprofiler2::gost(query = (cluster.trans %>% lapply(function(x)x$SYMBOL) %>% unlist %>% unname), organism = "hsapiens", significant = FALSE)
#openxlsx::write.xlsx(x = purrr::map(enrich.trans, ~.x$result), file = "./analysis/enrich_trans.xlsx")


# prot ext
cluster.prot.ext <- imap_dfr(PPI_cluster.ego, ~{V(.x)$name} %>% as.data.frame %>% set_names("molecule") %>% mutate(cluster = .y)) 
cov.ego <- AnnotationDbi::select(org.Hs.eg.db, keytype = "UNIPROT", keys = as.character(cluster.prot.ext$molecule), columns = c("SYMBOL"))
cluster.prot.ext <- left_join(cluster.prot.ext, cov.ego, by = c("molecule"="UNIPROT")) %>% 
    split(.$cluster)
enrich.prot.ext <- lapply(cluster.prot.ext, function(x) gprofiler2::gost(query = x$SYMBOL, organism = "hsapiens", significant = FALSE))
enrich.prot.ext[["all"]] <- gprofiler2::gost(query = (cluster.prot.ext %>% lapply(function(x)x$SYMBOL) %>% unlist %>% unname), organism = "hsapiens", significant = FALSE)

```

```{r ora2}
enr1<- enrich.mRNA$all$result
enr2<- enrich.prot$all$result
combine.pval <- function(enr1, enr2, enr3 = NULL, goterm_map){
    comb <- inner_join(enr1 %>% dplyr::select(p_value, term_id, query_size) %>% 
                           dplyr::rename("p_value_1" = "p_value", "query_size_1" = "query_size"),
               enr2 %>% dplyr::select(p_value, term_id, query_size) %>% 
                   dplyr::rename("p_value_2" = "p_value", "query_size_2" = "query_size"))
    if(!is.null(enr3)){
        comb <- inner_join(comb, enr3 %>% dplyr::select(p_value, term_id, query_size) %>% 
                               dplyr::rename("p_value_3" = "p_value", "query_size_3" = "query_size"))
    }
    comb <- comb %>%
        column_to_rownames("term_id") %>%
        t %>% as.data.frame() 
    print(ncol(comb))
    if(ncol(comb) == 0) {
        return(0)
    }
    comb.pvalue <- comb[rownames(comb) %>% str_detect("p_value"),,drop=FALSE]
    comb.weight <- comb[rownames(comb) %>% str_detect("query_size"),,drop=FALSE]
    
    term_map <- dplyr::select(enr1, c("term_id", "term_name")) %>%
        rbind(dplyr::select(enr2, c("term_id", "term_name"))) %>% unique
    
    if(!is.null(enr3)){
        term_map <- rbind(term_map, dplyr::select(enr3, c("term_id", "term_name"))) %>% unique
    }
    
    comb.res <- map2(comb.pvalue, comb.weight, ~{survcomp::combine.test(p = .x, weight = .y, method = "fisher")}) %>% 
        as.data.frame(check.names =FALSE) %>% t %>% as.data.frame(check.names =FALSE) %>%
        rownames_to_column("term_id") %>% dplyr::rename("comb.pvalue" = "V1")  %>%
        left_join(term_map , by = c("term_id"="term_id")) %>%
        mutate(adj.pval = p.adjust(.$comb.pvalue, method = "bonf"))
        
    
    #survcomp::combine.test(p = comb.pvalue$`GO:0007049`, method = "fisher", weight = comb.weight$`GO:0007049`)
    return(comb.res)
}
#combine.pval(enr1 = enrich.mRNA$all$result, enr2 = enrich.prot$all$result)
enrich.comb.mRNA.prot <- list()
enrich.comb.mRNA.trans <- list()
enrich.comb.mRNA.prot.trans <- list()
enrich.comb.mRNA.prot.ext <- list()


for(i in names(enrich.mRNA)){
    # mRNA - prot
    print(i)
    if(i %in% names(enrich.prot)){
        enrich.comb.mRNA.prot[[i]] <- combine.pval(enr1 = enrich.mRNA[[i]]$result, enr2 = enrich.prot[[i]]$result)
    } else{
        enrich.comb.mRNA.prot[[i]] <- NULL
    }
    # mrna - trans
    if(i %in% names(enrich.trans)){
        enrich.comb.mRNA.trans[[i]] <- combine.pval(enr1 = enrich.mRNA[[i]]$result, enr2 = enrich.trans[[i]]$result)
    } else{
        enrich.comb.mRNA.trans[[i]] <- NULL
    }
    # all
    if((i %in% names(enrich.trans)) & (i %in% names(enrich.prot))){
        enrich.comb.mRNA.prot.trans[[i]] <- combine.pval(enr1 = enrich.mRNA[[i]]$result, enr2 = enrich.prot[[i]]$result, enr3 = enrich.trans[[i]]$result)
    } else{
        enrich.comb.mRNA.prot.trans[[i]] <- NULL
    }
    if(i %in% names(enrich.prot.ext)){
        enrich.comb.mRNA.prot.ext[[i]] <- combine.pval(enr1 = enrich.mRNA[[i]]$result, enr2 = enrich.prot[[i]]$result, enr3 =enrich.prot.ext[[i]]$result )
    } else{
        enrich.comb.mRNA.prot.ext[[i]] <- NULL
    }
}
```

```{r ora3}
enrich.df_mRNA <- imap_dfr(enrich.mRNA, ~.x$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                               dplyr::select(term_id, source, p_value, cluster)) %>% filter(source %>% str_detect("GO:")) %>% 
    mutate(mode = "raw", type = "mRNA")

enrich.df_prot <- imap_dfr(enrich.prot, ~.x$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                               dplyr::select(term_id, source, p_value, cluster)) %>% filter(source %>% str_detect("GO:")) %>% mutate(mode = "raw", type = "prot")

enrich.df_trans <- imap_dfr(enrich.trans, ~.x$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                               dplyr::select(term_id, source, p_value, cluster)) %>% filter(source %>% str_detect("GO:"))  %>% mutate(mode = "raw", type = "trans")

enrich.df_prot.ext <- imap_dfr(enrich.prot.ext, ~.x$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                               dplyr::select(term_id, source, p_value, cluster)) %>% filter(source %>% str_detect("GO:"))  %>% mutate(mode = "extended", type = "prot")


enrich.df <- do.call("rbind", list(enrich.df_mRNA, enrich.df_prot,enrich.df_prot.ext, enrich.df_trans)) %>%
    mutate(approach = ifelse(cluster == "all", "all", "by_cluster") %>% factor(level = c("by_cluster", "all"))) %>%
    mutate(mode = factor(mode, levels = c("raw", "extended"))) 
```

production: "table_hela_ora.xlsx
```{r}
enrich.df.write <-  enrich.df %>% mutate(cluster = case_when(
    cluster == "Down_Up" ~ "Cluster_1",
    cluster == "Up_Up" ~ "Cluster_2",
    cluster == "Down_Down" ~ "Cluster_3",
    cluster == "Up_Down" ~ "Cluster_4",
    cluster == "all" ~ "all")) %>% split(.$type) 

enrich.df.write[["comb.p.value"]] <- imap_dfr(enrich.comb.mRNA.prot.trans, ~{.x %>% mutate(cluster = .y) %>% 
        filter(adj.pval <= 0.05) %>% 
        filter(str_detect(term_id, "GO:")) %>%
        mutate(cluster = case_when(
    cluster == "Down_Up" ~ "Cluster_1",
    cluster == "Up_Up" ~ "Cluster_2",
    cluster == "Down_Down" ~ "Cluster_3",
    cluster == "Up_Down" ~ "Cluster_4",
    cluster == "all" ~ "all"))
    })

openxlsx::write.xlsx(x = enrich.df.write, file = "./table_hela_ora.xlsx")
```

Connection 
```{r go_1}
go.info <- map_dfr(enrich.df$term_id %>% unique, ~get_go_info(.x))

enrich.df <- enrich.df %>% left_join(go.info, by = c("term_id"="name"))
save(enrich.df, file = "./enrich_all_filtered.rda")
```
```{r go_2}
load("./enrich_all_filtered.rda")

enrich.df %>% mutate(type = ifelse(mode == "raw", type, "Ext.")) %>%
    dplyr::select(term_id, source, type) %>% unique %>%
    group_by(source, type) %>%
    summarise(N = n()) %>%
    spread(source, N) %>% column_to_rownames('type') %>% .[c("mRNA","trans", "prot", "Ext."),]

enrich.df %>% filter(mode == "raw") %>% 
    #filter(type == "mRNA") %>% 
    group_by(type, cluster, source) %>%
    summarise(N = n()) %>%
    ggplot(aes(x = cluster, y = N, fill = source)) + geom_bar(stat = "identity", position = "dodge") +
    geom_text(aes(label = N), vjust=0.5, color="black",position = position_dodge(1)) +
    facet_grid(type~.)
    
    
tmp.go_terms <- enrich.df$term_id %>% map_df(~get_go_info(.x))
enrich.df %>% dplyr::select(mode, term_id, source, cluster, p_value) %>%
    filter(mode == "raw") %>% arrange(p_value) %>%
    left_join(tmp.go_terms, by = c('term_id' = 'name')) %>%
    filter(source %in% c("GO:BP", "GO:BP")) %>%
    dplyr::select(cluster, lab, description) %>% unique

enrich.df %>% dplyr::select(mode, term_id, source, cluster, p_value) %>%
    filter(mode == "raw") %>% arrange(p_value) %>%
    left_join(tmp.go_terms, by = c('term_id' = 'name')) %>%
    filter(source %in% c("GO:BP", "GO:BP")) %>%
    dplyr::select(cluster, source, lab, description) %>% unique %>%
    filter(source == "GO:MF")


# cluster specific and only visible in cluster (no global)
enrich.df %>% filter(mode == "raw") %>%
    dplyr::select(term_id, source, cluster, approach) %>%
    group_by(term_id, source) %>%
    summarise(N = n()) %>% filter(N == 1) %>% pull(term_id) -> tmp.unique.termi_id
enrich.df %>% filter(mode == "raw") %>% 
    filter(term_id %in% tmp.unique.termi_id) %>%
    left_join(tmp.go_terms, by = c('term_id' = 'name')) %>%
    unique() -> tmp.unique.cluster

#tmp.unique.cluster %>% filter(cluster != "all") %>% dplyr::select(cluster, description.x, lab.x) %>% filter(description.x %>% str_detect("BP"))

write_csv(tmp.unique.cluster, path = "./cs1_RWR_unique.csv")
```

```{r go3}
png("./figure/CS1_goterm_enr.png", height =  1500, width = 2000, res = 300)
enrich.df %>% mutate(approach = ifelse(approach == "by_cluster", "By_Cluster", "Global")) %>%
    mutate(mode = ifelse(mode == "raw", "Raw", "Extended") %>% factor(levels = c("Raw", "Extended"))) %>%
ggplot(aes(x = -log10(p_value), fill = mode)) +
    geom_histogram() +
    theme_bw() +
    scale_fill_manual(values = c("lightgrey", "black")) +
    theme(legend.position = "none") +
    facet_grid(approach~mode) +
    ylab("Number of GO terms")
dev.off()

png("./figure//CS1_goterm_enr_2.png", height =  1500, width = 2000, res = 300)
enrich.df %>% mutate(approach = ifelse(approach == "by_cluster", "By_Cluster", "Global")) %>%
    mutate(mode = ifelse(mode == "raw", "Raw", "Extended") %>% factor(levels = c("Raw", "Extended"))) %>%
    dplyr::select(term_id, source, type, mode, approach) %>% unique %>%
    group_by(source, mode, approach, type) %>%
    summarise(N = n()) %>% 
    filter(mode == "Raw") %>%
    group_by(type, mode, approach) %>%
    summarise(N = sum(N)) %>% 
    mutate(type = case_when(
        type == "mRNA" ~ "mRNA",
        type == "prot" ~ "Proteins",
        type == "trans" ~ "Trans. Products"
    ) %>% factor(levels = c("mRNA",  "Trans. Products", "Proteins"))) %>%
    ggplot(aes(x = approach, y = N, fill = type)) +
    geom_bar(stat = "identity", position = "dodge", width = 0.3, col = "black") +
    geom_text(aes(label = N), vjust=-0.5, color="black",position = position_dodge(0.3), size = 2) +
#    facet_grid(.~mode)  +
    theme_bw() + labs(fill = "Omic type", 
                      x = "Clustering approach", 
                      y = "Number of unique GO terms") +
    scale_fill_manual(values = c("#c9daf8", "#efefef", "#fce5cd"))
dev.off()

set.count.raw <-  enrich.df %>% filter(mode == "raw", cluster != "all") %>% split(.$cluster) %>% lapply(function(x) pull(x, term_id))
set.count.raw <- set.count.raw[c("Down_Up", "Up_Up", "Down_Down", "Up_Down")] 
names(set.count.raw) <- paste0("Cluster_", 1:4)
set.count.raw <- set.count.raw %>% make_comb_mat(min_set_size = 0)

set.count.ext <-  enrich.df %>% filter(mode == "extended", cluster != "all") %>% split(.$cluster) %>% lapply(function(x) pull(x, term_id)) 
set.count.ext[["Up_Down"]] <- c(1)
set.count.ext <- set.count.ext[c("Down_Up", "Up_Up", "Down_Down", "Up_Down")]
names(set.count.ext) <- paste0("Cluster_", 1:4)
set.count.ext <- set.count.ext %>% make_comb_mat(min_set_size = 0)

set.count.raw <- set.count.raw[union(comb_name(set.count.raw), comb_name(set.count.ext))]
set.count.ext <- set.count.ext[union(comb_name(set.count.raw), comb_name(set.count.ext))]

top_ha = HeatmapAnnotation(
    "Raw" = anno_barplot(comb_size(set.count.raw), gp = gpar(fill = "lightgrey"), height = unit(2, "cm")),
    "Extended" = anno_barplot(comb_size(set.count.ext), gp = gpar(fill = "black"), height = unit(2, "cm")),
    annotation_name_side = "left", annotation_name_rot = 0)

png("./figure//CS1_goterm_enr_3.png", height =  1300, width = 4000, res = 300)
UpSet(set.count.raw, top_annotation = top_ha,heigh = unit(5, "cm"), row_title = "Clusters")
dev.off()
```

```{r go4}
# all signif GO 
all_mol <- c(lapply(cluster.mRNA, function(x){x$molecule}) %>% base::unlist() %>% unname,
             lapply(cluster.prot, function(x){x$SYMBOL}) %>% base::unlist() %>% unname,
             lapply(cluster.trans, function(x){x$SYMBOL}) %>% base::unlist() %>% unname,
             lapply(cluster.prot.ext, function(x){x$SYMBOL}) %>% base::unlist() %>% unname) %>%
    unique %>% na.omit()
length(all_mol)

goterm_map <- gprofiler2::gconvert(query = all_mol, organism = "hsapiens", target = "GO") 
save(goterm_map, file = "./goterm_map.rda")


signif_goterm_map <- goterm_map %>% filter(target %in% enrich.df$term_id) %>%
    dplyr::select(input, target) %>% unique %>% na.omit()

signif_goterm_map$input %>% unique %>% length
signif_goterm_map$target %>% unique %>% length

signif_goterm_map.all <- rbind(signif_goterm_map, left_join(signif_goterm_map, conv.tab, by = c("input" = "SYMBOL")) %>% 
                                   na.omit() %>% dplyr::select("UNIPROT", "target") %>% set_names("input", "target")) %>%
    unique


GRN_PPI.ego.GO <- lapply(GRN_PPI.ego, add_go_term_layer)

imap_dfr(GRN_PPI.ego.GO, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y)}) %>%
    dplyr::select(type, name, cluster) %>% 
    #unique %>%
    group_by(type, cluster) %>%
    summarise(N = n()) %>% spread(type, N) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")

##############################
# for annotation full graph 
##############################

## unkown function
table(all_mol %in% unique(goterm_map$input))
table(unique(lapply(cluster.mRNA, function(x){x$molecule}) %>% base::unlist() %>% unname) %in% unique(goterm_map$input))
table(unique(lapply(cluster.prot, function(x){x$SYMBOL}) %>% base::unlist() %>% unname) %in% unique(goterm_map$input))
table(unique(lapply(cluster.trans, function(x){x$SYMBOL}) %>% base::unlist() %>% unname) %in% unique(goterm_map$input))
table(unique(lapply(cluster.prot.ext, function(x){x$SYMBOL}) %>% base::unlist() %>% unname) %in% unique(goterm_map$input))

unknown_seeds <- all_mol[!(all_mol %in% unique(goterm_map$input))] %>% unique
unknown_seeds_nodes <- c(do.call("rbind", cluster.mRNA) %>% mutate(seed = molecule) %>% filter(molecule %in% unknown_seeds) %>% na.omit() %>% pull(seed), 
                         do.call("rbind", cluster.prot) %>% mutate(seed = molecule) %>% filter(SYMBOL %in% unknown_seeds) %>%  na.omit() %>% pull(seed)
                         #do.call("rbind", cluster.trans) %>% mutate(seed = molecule) %>% filter(SYMBOL %in% unknown_seeds) %>% na.omit() %>% pull(seed)
                         #do.call("rbind", cluster.prot.ext) %>% mutate(seed = molecule) %>% mutate(type = "ext") %>% filter(SYMBOL %in% unknown_seeds) %>% na.omit() %>% pull(seed)
                         ) %>% unique


save(unknown_seeds, unknown_seeds_nodes, file ="./unknown_seeds.rda")
```


```{r}
load("./GO_graphs.rda")

vertex_attr(GOCC_graph)$type <- rep("GO:CC", vcount(GOCC_graph))
vertex_attr(GOBP_graph)$type <- rep("GO:BP", vcount(GOBP_graph))
vertex_attr(GOMF_graph)$type <- rep("GO:MF", vcount(GOMF_graph))

FINAL_GOBP <- add_go_term_annot(graph = GRN_PPI.ego$all, go.graph = as.undirected(GOBP_graph))
FINAL_GOCC <- add_go_term_annot(graph = GRN_PPI.ego$all, go.graph = as.undirected(GOCC_graph))
FINAL_GOMF <- add_go_term_annot(graph = GRN_PPI.ego$all, go.graph = as.undirected(GOMF_graph))

FINAL_GOBP_short <- add_go_term_annot(graph = GRN_PPI$all, go.graph = as.undirected(GOBP_graph))
FINAL_GOCC_short <- add_go_term_annot(graph = GRN_PPI$all, go.graph = as.undirected(GOCC_graph))
FINAL_GOMF_short <- add_go_term_annot(graph = GRN_PPI$all, go.graph = as.undirected(GOMF_graph))



tmp <- igraph::union(FINAL_GOBP, FINAL_GOCC)
vertex_attr(tmp) <- vertex_attr(tmp) %>% as.data.frame(stringsAsFactors = FALSE) %>% 
    mutate(type = ifelse(!is.na(type_1), type_1, type_2)) %>%
    dplyr::select(-c(type_1,type_2)) %>% as.list()
final_go_full <- igraph::union(tmp, FINAL_GOMF)
vertex_attr(final_go_full) <- vertex_attr(final_go_full) %>% as.data.frame(stringsAsFactors = FALSE) %>% 
    mutate(type = ifelse(!is.na(type_1), type_1, type_2)) %>%
    dplyr::select(-c(type_1,type_2)) %>% as.list()

save(GRN_PPI.ego.GO, final_go_full, FINAL_GOBP, FINAL_GOCC, FINAL_GOMF, FINAL_GOBP_short, FINAL_GOCC_short, FINAL_GOMF_short, file = "./GRN_PPI_GO.rda")

```

# Metabolite

```{r metabolite_1}
load("./reaction_mapformula_df.rda")

# kegg ko <-> rn <-> hsa
ko_reaction.list <- read_tsv("~/work/KEGGBD/ko/ko_reaction.list", col_names = c("ko", "rn"))
ko_enzyme.list <- read_tsv("~/work/KEGGBD/ko/ko_enzyme.list", col_names = c("ko", "ec"))
ko_gene.list <- read_tsv("~/work/KEGGBD/ko/ko_genes.list", col_names = c("ko", "gn"))

ko_reaction_enzyme_gene <- ko_reaction.list %>% full_join(ko_enzyme.list) %>% full_join(ko_gene.list)


tmp <- ko_reaction_enzyme_gene %>% filter(str_detect(gn, "hsa:")) %>%
    mutate(rn = str_remove(rn,"^rn:"), gn = str_remove(gn,"^hsa:")) %>%
    left_join(reaction_mapformula_df)

ENTREZID_lookup <- AnnotationDbi::select(org.Hs.eg.db, keytype = "ENTREZID", keys = tmp$gn,columns = c("UNIPROT")) %>%
    unique %>% na.omit

metab_uniprot <- tmp %>% left_join(ENTREZID_lookup, by = c("gn"="ENTREZID"))

METAB.graph <- igraph::graph_from_data_frame(metab_uniprot %>% dplyr::select(p1,p2) %>% unique %>% na.omit(), directed = FALSE)
interaction_met_prot.df <- metab_uniprot %>% dplyr::select(UNIPROT,p1,p2) %>% gather(p, met, -UNIPROT) %>% dplyr::select(-p) %>% unique %>% na.omit()
```

```{r metabolite_2}

################
# Add metabo layer
################

load(file = ".//GRN_PPI_GO.rda")


graph = GRN_PPI.ego.GO$all

interaction_met_prot.df %>% filter(UNIPROT %in% V(graph)$name) %>% pull(met) %>% unique %>% length
interaction_met_prot.df %>% filter(UNIPROT %in% V(graph)$name) %>% pull(UNIPROT) %>% unique %>% length

FULL_graph <- lapply(GRN_PPI.ego.GO, add_metabo_layer)



## add GO
#ko_go.list <- read_tsv(file = "~/work/KEGGBD/ko/ko_go.list", col_names = c("ko", "go"))
# ko2go <- ko_reaction_enzyme_gene %>% full_join(ko_go.list) %>% 
#     mutate(rn = str_remove(rn, "rn:")) %>%
#     left_join(reaction_mapformula_df) %>% dplyr::select(go, p1, p2) %>%
#     gather(p, cpd, -c(go)) %>%
#     dplyr::select(go, cpd) %>%
#     unique %>%
#     mutate(go = str_replace(go, "go:", "GO:"))
#save(ko2go, file = "./ko2go.rda")
load("./ko2go.rda")

#ko2go$cpd %in% (lapply(FULL_graph, function(x) V(x)$name) %>% unlist() %>% unname)
graph <- FULL_graph$all
#ko2go %>% filter(cpd %in% tmp$name & go %in% tmp$name)


FULL_graph <- lapply(FULL_graph, add_go_metabo_edges)
save(FULL_graph, file = "./graph_w_metabo.rda")


imap_dfr(FULL_graph, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y)}) %>%
    dplyr::select(type, name, cluster) %>% 
    #unique %>%
    group_by(type, cluster) %>%
    summarise(N = n()) %>% spread(type, N) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")
```


```{r cleaning}
# list prot only
prot_only <- lapply(PPI_cluster, function(x)V(x)$name) %>% unlist %>% unname
prot_ego <- setdiff(lapply(PPI_cluster.ego, function(x)V(x)$name) %>% unlist %>% unname, prot_only)
prot_ego <- map_dfr(PPI_cluster.ego, ~vertex_attr(.x)) %>% pull(name) %>% setdiff(prot_only)

prot_only <- imap_dfr(PPI_cluster, ~ vertex_attr(.x) %>% as.data.frame %>% mutate(cluster = .y))

gene_only <-  lapply(GRN.cluster, function(x)V(x)$name) %>% unlist %>% unname

metab_only <- map_dfr(FULL_graph, ~vertex_attr(.x) %>% as.data.frame) %>% filter(type == "Metabolite") %>% pull(name) %>% as.character()

go_only <-  map_dfr(GRN_PPI.ego.GO, ~vertex_attr(.x) %>% as.data.frame) %>% filter(type == "GO") %>% pull(name) %>% as.character()

FINAL <- purrr::imap(FULL_graph, ~reformate_graphs(graph = .x,cluster = .y ))

FINAL_GO_ANNOT <- list("BP" = FINAL_GOBP,
                       "CC" = FINAL_GOCC,
                       "MF" = FINAL_GOMF)
FINAL_GO_ANNOT <- purrr::map(FINAL_GO_ANNOT, ~reformate_graphs(graph = .x,cluster = "all" ))

FINAL_GO_ANNOT_short <- list("BP" = FINAL_GOBP_short,
                       "CC" = FINAL_GOCC_short,
                       "MF" = FINAL_GOMF_short)
FINAL_GO_ANNOT_short <- purrr::map(FINAL_GO_ANNOT_short, ~reformate_graphs(graph = .x,cluster = "all" ))

save(FINAL, FINAL_GO_ANNOT, FINAL_GO_ANNOT_short, file = './FINAL.rda')

imap_dfr(FINAL, ~{vertex_attr(.x) %>% as.data.frame() %>% mutate(cluster = .y)}) %>%
    dplyr::select(type, name, cluster) %>% 
    #unique %>%
    group_by(type, cluster) %>%
    summarise(N = n()) %>% spread(type, N) %>%
    mutate(cluster = factor(cluster, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(cluster) %>%
    column_to_rownames("cluster")
```

# Random Walk

## mechanisms
```{r rw_1}
load("unknown_seeds.rda")
load("enrich_all_filtered.rda")
list_go <- enrich.df %>% filter(mode == "raw", source == "GO:BP") %>% pull(term_id) %>% unique
list_go <- enrich.df  %>% pull(term_id) %>% unique
va.all <- vertex_attr(FINAL$all) %>% as.data.frame()

lapply(FINAL, function(x) table(V(x)$name %in% list_go))
lapply(FINAL, function(x) table(list_go %in% V(x)$name))
set.seed(1)
# RWR_go_mechanisms <- parallel::mclapply(FINAL, function(graph) {
#     parallel::mclapply(list_go, function(go) {homo_network_RWR(graph, seed = go, k = 25)}, mc.cores = 20)}, 
#     mc.cores = 4)
# Sys.time()
load("./RWR_res_mechanisms.rda")
```

```{r rw2}
RWR_go_mechanisms <- lapply(RWR_go_mechanisms, function(x) `names<-`(x, list_go))
graph <- RWR_go_mechanisms$all$`GO:0005515`
length(RWR_go_mechanisms$all)  # nb go term tested

RWR_go_mechanisms_annot <- lapply(names(RWR_go_mechanisms), function(x){
    imap_dfr(RWR_go_mechanisms[[x]], ~{ mechanisms_annot(.x, .y)}) %>%
        mutate(CLUSTER = x)}) %>%
    do.call(what = "rbind")
write.csv(RWR_go_mechanisms_annot, file = "./RWR_meca.csv")
```

```{r rwr3}
RWR_go_mechanisms_annot_tmp <- RWR_go_mechanisms_annot %>% 
    group_by(CLUSTER, seed, type) %>%
    summarise(N=n()) %>% spread(type, N) 
RWR_go_mechanisms_annot_tmp[is.na(RWR_go_mechanisms_annot_tmp)] <- 0


good_go_list.df <- enrich.df %>% filter(mode == "raw") %>% dplyr::select(term_id, source, description) %>%
    unique %>% filter(source == "GO:BP") 
# 
# RWR_go_mechanisms_annot_tmp %>% filter(Metabolite>0, Gene >0, Prot>0) %>%
#     left_join(map_dfr(.$seed %>% unique, ~get_go_info(.x)), by = c("seed"="name")) 
#     
# RWR_go_mechanisms_annot_tmp %>% filter(Metabolite>0, Gene >0, Prot>0) %>% 
#     left_join(good_go_list.df, by = c("seed"="term_id")) %>%
#     na.omit


# exported result along with seed <-> molecule (va)
tmp_meca <- RWR_go_mechanisms_annot_tmp %>%  
    left_join(enrich.df %>% dplyr::select(term_id, source, mode, description) %>% unique, by = c("seed"="term_id")) 
#write.csv(tmp_meca, file = ".//RWR_meca_stats.csv")
#tmp_meca <- read.csv(".//RWR_meca_stats.csv")

# gene and protein and metabolite
tmp_meca %>%
    filter(mode == "raw") %>%  # only based enriched GO // not extended
    filter(Metabolite>0, Gene >0, Prot>0) %>%
    dplyr::select(seed, description, source, CLUSTER) %>%
    group_by(source, CLUSTER) %>%
    summarise(N=n()) %>% spread(source, N) %>%
    mutate(CLUSTER = factor(CLUSTER, levels = c("Down_Up", "Up_Up", "Down_Down", "Up_Down", "all"))) %>%
    arrange(CLUSTER)

tmp_meca %>%
    filter(mode == "raw") %>%
    filter(Gene >0, Prot>0)  %>%
    mutate(approach = ifelse(CLUSTER == "all", "all", "by_cluster"))  %>%
    ungroup() %>%
    dplyr::select(approach, seed, source) %>% unique %>%
    group_by(approach, source) %>% summarise(N=n()) %>% spread(source, N)


tmp_meca %>%
    filter(mode == "raw") %>%  # only based enriched GO // not extended
    filter(Metabolite>0, Gene >0, Prot>0) %>%
    dplyr::select(seed, description, source, CLUSTER) %>%
    group_by(CLUSTER, seed, description, source) %>%
    summarise(N = n()) %>%
    spread(CLUSTER, N) %>%
    mutate(SUM = sum(all, Down_Down, Down_Up, Up_Up, na.rm = TRUE)) %>%
    filter(SUM == 1)

### PLOT FIGURE
#tmp_meca %>% filter(seed == 'GO:0007088')
plot.graph.tmp <- RWR_go_mechanisms$all[["GO:0007088"]]
l <- layout_nicely(plot.graph.tmp)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)
seed.plot = "GO:0007088"
# plot.graph.tmp <- RWR_go_mechanisms$all[["GO:0034968"]]
vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>% as.data.frame() %>% left_join(va.all) %>%
    mutate(color = ifelse(name == seed.plot, "red", color)) 
vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>%
    mutate(color = ifelse(type == "Prot.ego", "orange", color),
           frame.color = ifelse(type %in% c("Prot.ego", "Metabolite"), "red", "darkgrey"),
           size = ifelse(type %in% c("Prot.ego", "Metabolite"), 5,6), 
           size = ifelse(name == seed.plot, 8, size))

png("./figure/cs1_rwr_meca.png", height =  3000, width = 3500, res = 300)
plot(plot.graph.tmp, layout=l)
legend("bottomleft", 
       legend = c("SEED", "Genes", "Proteins", "Metabolites", "GO terms", "Ext. neighbours"),
       col = c("red", "lightblue", "orange", "green", "lightgrey", "red"),
       pch = c(19, 19, 19, 19, 19, 1),
       pt.cex = c(1.5, 1, 1, 1, 1, 1.5), 
       cex = 1.3,
       box.col="white"
)
title("Regulation of mitotic nuclear division")
dev.off()
```

```{r}
### PLOT FIGURE
tmp_meca %>% filter(seed == 'GO:0007088')
plot.graph.tmp <- RWR_go_mechanisms$all[["GO:0007088"]]
l <- layout_nicely(plot.graph.tmp)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)
seed.plot = "GO:0007088"
# plot.graph.tmp <- RWR_go_mechanisms$all[["GO:0034968"]]
#vertex_attr(plot.graph.tmp) <- 
vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>% as.data.frame() %>% left_join(va.all) %>%
    mutate(color = ifelse(name == seed.plot, "red", color)) 
vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>%
    mutate(color = ifelse(type == "Prot.ego", "orange", color),
           frame.color = ifelse(type %in% c("Prot.ego", "Metabolite"), "red", "darkgrey"),
           size = ifelse(type %in% c("Prot.ego", "Metabolite"), 5,6), 
           size = ifelse(name == seed.plot, 8, size))

png("./figure/cs1_rwr_meca.png", height =  3000, width = 3500, res = 300)
plot(plot.graph.tmp, layout=l)
legend("bottomleft", 
       legend = c("SEED", "Genes", "Proteins", "Metabolites", "GO terms", "Ext. neighbours"),
       col = c("red", "lightblue", "orange", "green", "lightgrey", "red"),
       pch = c(19, 19, 19, 19, 19, 1),
       pt.cex = c(1.5, 1, 1, 1, 1, 1.5), 
       cex = 1.3,
       box.col="white"
)
title("Regulation of mitotic nuclear division")
dev.off()

# stat
stat_table <- function(list_g){
    res <- imap_dfr(list_g, ~.x %>% 
                        vertex_attr %>%
                        mutate(type = factor(type, levels = levels(va.all$type))) %>% 
                        pull(type) %>% table %>% as.data.frame() %>% 
                        column_to_rownames(".") %>% set_names(.y) %>%
                        t %>% as.data.frame() %>% rownames_to_column("seed"))
    return(res)
}
stat_rwr_cluster <- imap_dfr(good_go_cluster, ~stat_table(.x) %>% mutate(cluster=.y)) 
stat_rwr_all <- stat_table(good_go_all) %>% mutate(cluster="all")

stat_rwr_cluster %>% 
    arrange(desc(Gene, Prot, Prot.ego, Metabolite, go_term)) %>%
    filter(Metabolite >0) %>%
    mutate(seed = factor(seed, levels = unique(.$seed))) %>%
    gather(type, value, -c(seed, cluster)) %>% left_join(dplyr::select(va.all, c(type, color, lab)) %>% unique) %>%
    ggplot(aes(x=seed, y=value, fill = lab)) + geom_bar(stat = "identity") +
    facet_grid(~cluster,scales = "free_x", space = "free") +
    scale_fill_manual(values = dplyr::select(va.all, c(type, color, lab)) %>% unique %>% arrange(type) %>% pull(color)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    xlab(label = "Seed (GO terms)") + ylab("Number of molecules") +
    guides(fill = guide_legend("Type of molecule")) +
    ggtitle("Random Walk Result with a multi-omics hits")

stat_rwr_all %>% 
    arrange(desc(Gene, Prot, Prot.ego, Metabolite, go_term)) %>%
    filter(Metabolite >0) %>%
    mutate(seed = factor(seed, levels = unique(.$seed))) %>%
    gather(type, value, -c(seed, cluster)) %>% left_join(dplyr::select(va.all, c(type, color, lab)) %>% unique) %>%
    ggplot(aes(x=seed, y=value, fill = lab)) + geom_bar(stat = "identity") +
    facet_grid(~cluster,scales = "free_x", space = "free") +
    scale_fill_manual(values = dplyr::select(va.all, c(type, color, lab)) %>% unique %>% arrange(type) %>% pull(color)) +
    theme_bw() +
    theme(axis.text.x = element_text(angle = 90, hjust = 1)) +
    xlab(label = "Seed (GO terms)") + ylab("Number of molecules") +
    guides(fill = guide_legend("Type of molecule")) +
    ggtitle("Random Walk Result with a multi-omics hits")

# list of molecule without go
graph <- FINAL$all
with_go_annotation <- function(graph, node){
    ego <- make_ego_graph(graph = graph, nodes = node, order = 1)[[1]]
    va <- vertex_attr(ego) %>% as.data.frame() %>% na.omit()
    return(any(va$type == "GO"))
}




######################################
# 2. Get annotation SEED = unknown
######################################


# get annotation
# nodes <- V(graph)$name
# nodes_with_go <- lapply(nodes, function(x)with_go_annotation(graph = graph, node = x))
load("./unknown_seeds.rda")

find_annotation <- function(graph, seed){
    seed <- seed[seed %in% V(graph)$name]
    if(is_empty(seed)){
        return(NULL)
    }
    network <- extract_component(graph, seed)[[1]]
        
    MultiplexObject <- RandomWalkRestartMH::create.multiplex(network, Layers_Name = c("component"))
    AdjMatrix <- compute.adjacency.matrix(MultiplexObject)
    AdjMatrixNorm <- normalize.multiplex.adjacency(AdjMatrix)   
    
        
    RWR_Results <- Random.Walk.Restart.Multiplex(AdjMatrixNorm, MultiplexObject,seed)
    return(RWR_Results)
}

# 
# test <- find_annotation(FINAL_GO_ANNOT$BP, unknown_seeds[[1]])
# res <- as.list(unknown_seeds)
# names(res) = unknown_seeds
# for(i in unknown_seeds){
#     print(i)
#     #res[[i]] <- find_annotation(FINAL_GO_ANNOT$BP, i)
#     res[[i]] <- find_annotation(FINAL$all, i)
# }
# 
# 
# #save(res, file = "./analysis/RWR_annot.rda")
# load("./analysis/RWR_annot.rda")
# lapply(res, class) %>% unlist %>% table
# RES <- res[lapply(res, function(x)class(x) == "RWRM_Results") %>% unlist]
# 
annot_RWR_res <- function(RWR){
    
    if(is(RWR,"try-error") || is.null(RWR$RWRM_Results)){
        return(as.data.frame(list(NodeNames = NA, Score = NA, position = NA)))
    }
    RWR$RWRM_Results %>% #left_join(va.all, by = c("NodeNames"= "name")) %>%
        mutate(position = seq(1,nrow(.))) %>% #pull(type) %>% unique
        #filter(type == "go_term") %>%
        filter(NodeNames %>% str_detect("GO:")) %>%
        dplyr::top_n(n = -1, wt = position) %>%
        dplyr::select(NodeNames, Score, position)
        # pull(position)
}
# 
# go_pos <- lapply(RES, annot_RWR_res)

# final strategie

# 1. aggregé
purrr::map(FINAL_GO_ANNOT_short,  ~table(unknown_seeds_nodes %in% V(.x)$name)) 

unknown_seeds_nodes[purrr::map(FINAL,  ~as.numeric(unknown_seeds_nodes %in% V(.x)$name)) %>% as.data.frame() %>%
    rowSums() > 0]

res <- as.list(unknown_seeds_nodes)
names(res) = unknown_seeds_nodes

RES_aggregation <- parallel::mclapply(FINAL_GO_ANNOT_short, function(graph){
    parallel::mclapply(res, function(seed){
        find_annotation(graph = graph, seed = seed)
    }, mc.cores = 8)
}, mc.cores = 8)

# 2. heterogeity: split
load(file = "./goterm_map.rda")
interaction.df = goterm_map %>% dplyr::select(input, target) %>% unique
find_annot_RWR_het <- function(graph, seed, interaction.df){
    va <- vertex_attr(graph) %>% as.data.frame()
    go_nodes <- filter(va, type == "go_term") %>% pull(name)
    go_graphS <- igraph::subgraph(graph = graph, v = go_nodes) %>% igraph::decompose()
    
    other_nodes <- filter(va, type != "go_term") %>% pull(name)
    other_graph <- igraph::subgraph(graph = graph, v = other_nodes)
    
    bipartite.all  <- interaction.df %>% filter(input %in% other_nodes, target %in% go_nodes)
    
    # RWR
    seed <- seed[seed %in% V(other_graph)$name]
    if(is_empty(seed)){
        return(NULL)
    }
    Network_1 <- extract_component(other_graph, seed)[[1]]
    Network_1_MultiplexObject <- create.multiplex(Network_1, Layers_Name = c("Molecule"))
    
    
    bip <- lapply(go_graphS, function(gg){bipartite.all %>% filter(target %in% V(gg)$name, input %in% V(Network_1)$name)})
    index <- lapply(bip, function(x) ifelse(nrow(x) >0, TRUE, FALSE)) %>% unlist
    index2 <- lapply(go_graphS, function(x) ifelse(vcount(x) >1, TRUE, FALSE)) %>% unlist
    
    bip <- bip[index & index2]
    go_graphS <- go_graphS[index & index2]
    
    res_rwr <- list()
    for(i in 1:length(go_graphS)){
        
        Network_2 <- go_graphS[[i]]
        interaction.bip <- bip[[i]]
        MultiplexHetObject <- create.multiplexHet(Multiplex_object = Network_1_MultiplexObject, 
                                                  Network_2,
                                                  Nodes_relations = interaction.bip, 
                                                  SecondNetworkName =  c("GO_TERM"))
        HetTranMatrix <- compute.transition.matrix(MultiplexHetObject)
        
        # seed go ?
        full_network <- igraph::union(Network_1, 
                                      igraph::graph_from_data_frame(interaction.bip, directed = FALSE),
                                      Network_2)
        
        #SeedGO <- V(Network_2)$name[1]
        # short_path <- igraph::shortest.paths(full_network)
        # SeedGO <- short_path%>% as.data.frame() %>% rownames_to_column("node1") %>% 
        #     gather(node2, distance, -node1) %>%
        #     filter(node1 %in% seed) %>%
        #     filter(node2 %in% V(Network_2)$name) %>%
        #     top_n(wt = distance, n = -1) %>% pull(node2)
        SeedGO <- NULL
        res_rwr[[i]] <- Random.Walk.Restart.MultiplexHet(x = HetTranMatrix,
                                                                     MultiplexHetObject,
                                                                     seed,
                                                                     SecondNet_Seed_Nodes = SeedGO)
    }
 return(res_rwr)
}

RES_het <- parallel::mclapply(FINAL_GO_ANNOT_short, function(graph){
    parallel::mclapply(res, function(seed){
        find_annot_RWR_het(graph = graph, seed = seed, interaction.df = interaction.df)
    }, mc.cores = 8)
}, mc.cores = 8)

# save(RES_aggregation, RES_het, file = "./analysis/RWR_find_annotations.rda" )
#save(RES_aggregation, RES_het, RWR_go_mechanisms, file = "./analysis/RWR_all_res.rda")
## explore result
load("./RWR_find_annotations.rda")

# load("./RES_het.rda")
# load("./RWR_RES_aggregation.rda")

#short_path <- lapply(FINAL_GO_ANNOT_short, function(x) igraph::shortest.paths(x))

tmp.aggregation <- imap_dfr(RES_aggregation$BP, ~annot_RWR_res(.x) %>% mutate(type = "BP", seed = .y)) %>% na.omit() %>% rbind(
imap_dfr(RES_aggregation$CC, ~annot_RWR_res(.x) %>% mutate(type = "CC", seed = .y)) %>% na.omit()) %>% rbind(
imap_dfr(RES_aggregation$MF, ~annot_RWR_res(.x) %>% mutate(type = "MF", seed = .y)) %>% na.omit()) %>% 
    left_join(map_dfr(.$NodeNames %>% unique, ~get_go_info(.x)), by = c("NodeNames"="name"))  %>%
    mutate(mode = "monoplex")


RES_RWR_het <- RES_het$BP$KIAA1671
RES_RWR_het <- RES_het$BP$CCDC18

.merge_res_het <- function(RES_RWR_het, i){
    # print(RES_RWR_het$Multiplex_Seed_Nodes)
    first_result <- RES_RWR_het$RWRMH_Results_MultiplexNodes #%>%
    # left_join(va.all, by = c("NodeNames"= "name")) 
    second_result <- RES_RWR_het$RWRMH_Results_SecondNetNodes %>%
        # left_join(va.all, by = c("SecondNet_node"= "name")) %>%
        dplyr::rename(NodeNames = SecondNet_node)
    rbind(first_result, second_result) %>% 
        mutate(position = order(Score, decreasing = TRUE)) %>%
        #filter(type %in% c("go_term")) %>%
        filter(str_detect(NodeNames, "GO:")) %>%
        mutate(composition = i)
}

filtre_res_het <- function(RES_RWR_het){
    if(is.null(RES_RWR_het) || is(RES_RWR_het, "try-error")){
        tmp <- list("NodeNames" = character(), "Score" = numeric(), position = integer(), composition = integer()) %>% as.data.frame(stringsAsFactor = FALSE) %>% na.omit()
        return(tmp)
    } else {
        tmp <- imap_dfr(RES_RWR_het, ~.merge_res_het(.x, .y)) %>% 
            dplyr::top_n(wt = position, n = -1) %>%
            dplyr::top_n(wt = Score, n = 1)
        return(tmp)
    }
}

het_BP <- imap_dfr(RES_het$BP, ~filtre_res_het(.x) %>% mutate(type = "BP", seed = .y)) %>% na.omit() %>% mutate(mode = "heterogeneous")
het_MF <- imap_dfr(RES_het$MF, ~filtre_res_het(.x) %>% mutate(type = "MF", seed = .y)) %>% na.omit() %>% mutate(mode = "heterogeneous")
het_CC <- imap_dfr(RES_het$CC, ~filtre_res_het(.x) %>% mutate(type = "CC", seed = .y)) %>% na.omit() %>% mutate(mode = "heterogeneous")

tmp.heterogeneous <- rbind(het_BP, het_MF, het_CC) %>% left_join(map_dfr(.$NodeNames %>% unique, ~get_go_info(.x)), by = c("NodeNames"="name")) 
#lapply(FINAL_GO_ANNOT_short, function(x) sum(unknown_seeds %in% V(x)$name))

tmp.melt <- rbind(tmp.aggregation, tmp.heterogeneous %>% dplyr::select(-"composition")) %>%
    dplyr::select(lab, seed, type, mode, position, description) %>%
    spread(mode, position) %>%
    rename("lab" = "go") %>%
    dplyr::select(seed, type, go, description, monoplex, heterogeneous)
write_csv(tmp.melt, path = "./RWR_annotations.csv")
tmp.melt %>% split(.$seed)

#####################
# 3. in between nodes
#####################
load("./luster_info.rda")
load("./FINAL.rda")
#load("./unknown_seeds.rda")

graph <- FINAL$all
SEEDS <- cluster.info %>% filter(block %in% c("mRNA", "prot")) %>%
    mutate(molecule = molecule %>% str_remove("mRNA_") %>% str_remove("prot_")) %>%
    filter(molecule %in% V(graph)$name) %>%
    #pull(block) %>% table
    pull(molecule)

in_between <- function(graph, seed, k = 10){
    seed <- seed[seed %in% V(graph)$name]
    if(is_empty(seed)){
        return(NULL)
    }
    network <- extract_component(graph, seed)[[1]]
    
    MultiplexObject <- RandomWalkRestartMH::create.multiplex(network, Layers_Name = c("component"))
    AdjMatrix <- compute.adjacency.matrix(MultiplexObject)
    AdjMatrixNorm <- normalize.multiplex.adjacency(AdjMatrix)   
    
    
    RWR_Results <- Random.Walk.Restart.Multiplex(AdjMatrixNorm, MultiplexObject,seed)
    TopResults  <- create.multiplexNetwork.topResults(RWR_Results,MultiplexObject,k=k)
    return(TopResults)
}

res <- as.list(SEEDS)
names(res) = SEEDS
for(i in SEEDS){
    print(i)
    #res[[i]] <- find_annotation(FINAL_GO_ANNOT$BP, i)
    res[[i]] <- in_between(FINAL$all, i, k = 10)
}
# save(res, file = "./RWR_between.rda")
load("./RWR_between.rda")

graph <- res$Q8NI77
seed_name <- "Q8NI77"
va.all <- vertex_attr(FINAL$all) %>% as.data.frame()
detect_intersection <- function(graph, seed_name){
    va <- vertex_attr(graph) %>% as.data.frame() %>%
    left_join(cluster.info %>% mutate(molecule = molecule %>% str_remove("mRNA_") %>% str_remove("prot_")), by = c("name"="molecule"))

    cluster_seed <- va %>% filter(name == seed_name) %>% pull(cluster)
    tmp <- va %>% filter(!is.na(cluster)) %>%
        mutate(cluster.seed = cluster_seed) %>%
        mutate(cluster.mol = ifelse(name == seed_name, cluster.seed, cluster)) %>%
        mutate(between = (cluster.seed != cluster.mol)) 
    flag <- tmp %>% pull(between) %>% any
    if(flag){
        to_return <- vertex_attr(graph) %>% as.data.frame() %>% 
            left_join(va.all) %>%
            filter(type == "go_term")
        # add go lab
        if(any(to_return$type == "go_term")){
            to_return <- left_join(to_return, map_dfr(to_return$name, ~get_go_info(.x)), by = c("name"="name")) %>%
                dplyr::select(name, description)  %>%
                mutate(seed = seed_name, cluster.seed = cluster_seed, cluster.mol = NA)
        }
        to_return <- tmp %>% filter(between) %>% mutate(seed = seed_name) %>%
            dplyr::select(seed, name, cluster.seed, cluster.mol) %>%
            mutate(description = NA) %>%
            rbind(to_return)
        return(to_return)
    }
    return(NULL)
}
detect_intersection(res$ANLN, seed_name = "ANLN")
res_between_intersection <- imap(res, ~detect_intersection(.x, seed_name = .y))
res_between_intersection %>% lapply(is.null) %>% unlist %>% table
res_between_intersection_with_go <-  res_between_intersection[res_between_intersection %>% lapply(nrow) %>% unlist %>% subset(.>0) %>% names] %>%
    imap_dfr(~{.x %>% mutate(seed = .y)}) %>% dplyr::select(seed, name, description)

write_csv(x = res_between_intersection_with_go, path = "./results/RWR_cluster_intersection.csv")

# != go terms
res_between_intersection_with_go %>% filter(name %>% str_detect("GO:")) %>% group_by(name, description) %>% summarise(N = n()) %>% arrange(desc(N)) %>%
    mutate(source = description %>% str_extract("....$")) %>% split(.$source)

# seed with != cluster and GO terms
res_between_intersection_with_go %>% filter(name %>% str_detect("GO:")) %>% pull(seed) %>% unique %>% length

# example
res_between_intersection_with_go %>% filter(seed %in% (res_between_intersection_with_go %>% filter(name == "GO:0051301") %>% pull(seed)))
va.all %>% filter(name %in% c("PIMREG", "H6PD", "SETD1B"))
res_between_intersection[["PIMREG"]]
igraph::make_ego_graph(FINAL$all, nodes = "PIMREG", order = 1) %>% .[[1]] %>% vertex_attr() %>% as.data.frame() %>%
    left_join(cluster.info %>% mutate(molecule = molecule %>% str_remove("mRNA_")),by = "molecule")

res_between_intersection_with_go %>% filter(seed %in% (res_between_intersection_with_go %>% filter(name == "GO:0007275") %>% pull(seed)))


openxlsx::write.xlsx(x = list("mechanism" = RWR_go_mechanisms_annot, "prediction" = tmp.heterogeneous, "cluster" = res_between_intersection_with_go),
                     file = "./results/table_hela_rwr.xlsx")

### PLOT FIGURE
plot.graph.tmp <- res$PIMREG
l <- layout_nicely(plot.graph.tmp)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)
seed.plot = "PIMREG"
plot.graph.tmp <- res$PIMREG
vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>% as.data.frame() %>% left_join(va.all) %>%
    dplyr::select(-cluster) %>% left_join(cluster.info %>% filter(block == "mRNA") %>% mutate(molecule = molecule %>% str_remove("mRNA_")), by = c("name"="molecule")) %>%
    mutate(color = ifelse(name == seed.plot, "red", color)) %>%
    mutate(cluster = case_when(
        cluster == "Down_Up" ~ "Cluster 1", 
        cluster == "Up_Up" ~ "Cluster 2",
        cluster == "Down_Down" ~ "Cluster 3",
        cluster == "Up_Down" ~ "Cluster 4",
    )) 

vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>%
    mutate(color = ifelse(type == "Prot.ego", "orange", color),
           #frame.color = ifelse(type %in% c("Prot.ego", "Metabolite"), "red", "darkgrey"),
           size = ifelse(type %in% c("Prot.ego", "Metabolite"), 5,6), 
           size = ifelse(name == seed.plot, 8, size),
           frame.color = case_when(
               cluster == "Cluster 1" ~ "darkgreen",
               cluster == "Cluster 2" ~ "orange",
               cluster == "Cluster 3" ~ "purple",
               cluster == "Cluster 4" ~ "orange",
               TRUE ~ "grey"))


png("./figure/cs1_rwr_cluster.png", height =  3000, width = 3500, res = 300)
plot(plot.graph.tmp, layout=l)
legend("topleft", 
       legend = c("SEED", "Genes", "GO terms"),
       col = c("red", "lightblue", "lightgrey"),
       pch = c(19, 19, 19),
       pt.cex = c(1.5, 1, 1), 
       cex = 1.3,
       box.col="white"
)
legend("bottomright", 
       legend = paste0("Cluster ", 1:2),
       col = c("darkgreen", "orange"),
       pch = c(1),
       cex = 1.3,
       box.col="white")
title("PIMREG\n(PICALM Interacting Mitotic Regulator)")
dev.off()

load("./data_filtered.rda")
tmp.no.model<- mRNA.fc %>%
    rownames_to_column("sample") %>% 
    mutate(time = sample %>% str_remove("_Rep.")) %>%
    gather(name, value, -c(time, sample)) %>%
    mutate(name = name %>% str_remove("mRNA_")) %>%
    filter(name %in% vertex_attr(plot.graph.tmp)$name) %>%
    mutate(time = case_when(
        time == "G1" ~ 1,
        time == "S" ~ 2, 
        time == "G2/M" ~3)) %>% left_join( vertex_attr(plot.graph.tmp)) %>% 
    dplyr::select(time, name, value, cluster) %>%
    # mutate(cluster = case_when(
    #     cluster == "Down_Up" ~ "Cluster 1", 
    #     cluster == "Up_Up" ~ "Cluster 2",
    #     cluster == "Down_Down" ~ "Cluster 3",
    #     cluster == "Up_Down" ~ "Cluster 4",
    # )) %>%    
    arrange(cluster) 
order.name <- tmp.no.model$name %>% unique


tmp.no.model<- tmp.no.model %>% mutate(name = factor(name, levels = order.name))
# long clustering
tmp.model <- mRNA.filter %>%  rownames_to_column("time") %>%
    gather(name, value, -time) %>%
    mutate(name = name %>% str_remove("mRNA_")) %>%
    left_join(vertex_attr(plot.graph.tmp)) %>%
    filter(!is.na(cluster)) %>%
    dplyr::select(time, name, value, cluster) %>%
    mutate(time = as.numeric(time)) %>%
    # mutate(cluster = case_when(
    #     cluster == "Down_Up" ~ "Cluster 1", 
    #     cluster == "Up_Up" ~ "Cluster 2",
    #     cluster == "Down_Down" ~ "Cluster 3",
    #     cluster == "Up_Down" ~ "Cluster 4",
    # ))  %>%
    mutate(name = factor(name, levels = order.name))


png("./figure/cs1_rwr_cluster_dyn.png", height =  2500, width = 2000, res = 300)
ggplot(tmp.model, aes(x=time, y=value, group = name, col = cluster)) + geom_line() +
    geom_point(data = tmp.no.model) +
    #facet_wrap(name~., dir = "v", ncol = 1, scales = "free") +
    facet_grid(name~., scales = "free") +
    
    theme_bw() +
    scale_color_manual(values = c("darkgreen", "orange")) +
    labs(x = "Time", y = "Expression value", col = "Cluster") +
    theme(legend.position = "top")
dev.off()
```

