---
title: "CS2: Maize Aphids Feeding"
output: html_document
---

```{r, echo = F}
knitr::opts_chunk$set(cache = TRUE)
dir.create("./figure")
```

```{r, message=FALSE, cache=F}
library(tidyverse)
library(mixOmics)
library(timeOmics)
library(igraph)
library(minet)
library(gprofiler2)
library(RandomWalkRestartMH)
library(GO.db)
library(ComplexHeatmap)
```


```{r, cache=FALSE}
source("./CS2_utils.R")
```


# Preprocessing

## Genes

```{r gene_preprocessing, message=FALSE}
diff.genes <- read_csv(file = "data/Table_3.csv", skip = 2)

all.genes <- read_csv(file = "data/Table_1.csv", skip = 3) %>% dplyr::select(-contains("96h"))

ALL.genes.diff <- all.genes %>% as.data.frame() %>% 
    filter(`Gene IG` %in% diff.genes$`Gene ID`) %>%
    column_to_rownames('Gene IG') %>%
    dplyr::select(contains("ctr") | contains("sample"))

ALL.genes.sample <- ALL.genes.diff %>% 
    dplyr::select(contains("sample")) 

ALL.genes.ctr <- ALL.genes.diff %>% 
    dplyr::select(contains("ctr")) 

# get TF coding genes from PPIM: http://comp-sysbio.org/ppim/download/TF_formatted.txt
TF.raw <- read_tsv("data/TF_formatted.txt", col_names = FALSE) %>%
    mutate(X1 = X1 %>% str_remove("_P..$"))
TF.list <- (TF.raw$X1 %in% rownames(ALL.genes.sample))

TF.sample <- ALL.genes.sample[rownames(ALL.genes.sample) %in% TF.raw$X1,]
genes.sample <- ALL.genes.sample[!(rownames(ALL.genes.sample) %in% TF.raw$X1),]

TF.ctr <- ALL.genes.ctr[rownames(ALL.genes.sample) %in% TF.raw$X1,]
genes.ctr <- ALL.genes.ctr[!(rownames(ALL.genes.sample) %in% TF.raw$X1),]
```

```{r FC, fig.align="center"}
# FC threshold
par(mfrow=c(2,2))
genes.sample.fc <- remove.fold.change(X = t(genes.sample), cutoff = log(2), hist.title = "SAMPLES -- genes -- 5TP FC")
genes.ctr.fc <- remove.fold.change(X = t(genes.ctr), cutoff = log(2), hist.title = "CTRL -- genes -- 5TP FC")
TF.sample.fc <- remove.fold.change(X = t(TF.sample), cutoff = log(2), hist.title = "SAMPLES -- TF -- 5TP FC")
TF.ctr.fc <- remove.fold.change(X = t(TF.ctr), cutoff = log(2), hist.title = "CTRL -- TF -- 5TP FC")
par(mfrow=c(1,1))
```

```{r lmms, warning=FALSE, message=FALSE}
time = rownames(genes.sample.fc) %>% str_extract("_.*h") %>% str_remove("_") %>% str_remove("h") %>% as.numeric()
sampleID = rownames(genes.sample.fc)
X = as.data.frame(log(genes.sample.fc +1))
gene.lmms.5tp <- wrapper.lmms.5tp(X, time, sampleID)
gene.lmms.5tp$summary

time = rownames(TF.sample.fc) %>% str_extract("_.*h") %>% str_remove("_") %>% str_remove("h") %>% as.numeric()
sampleID = rownames(TF.sample.fc)
X = as.data.frame(log(TF.sample.fc +1))
TF.lmms.5tp <- wrapper.lmms.5tp(X, time, sampleID)
TF.lmms.5tp$summary
```

```{r lmms_filter}
genes.lmms.filter <- lmms.filter.lines(data = gene.lmms.5tp$X, 
                                       lmms.obj = gene.lmms.5tp$pspline, time = time)
genes.lmms.filtered.5tp <- genes.lmms.filter$filtered
genes.lmms.filtered.5tp.no_model <- gene.lmms.5tp$X %>% dplyr::select(colnames(genes.lmms.filtered.5tp))
genes.lmms.filtered.5tp.no_model.ctrl <- genes.ctr %>% t %>% as.data.frame() %>% `+`(1) %>% log %>%
    dplyr::select(colnames(genes.lmms.filtered.5tp.no_model)) 

TF.lmms.filter <- lmms.filter.lines(data = TF.lmms.5tp$X, 
                                    lmms.obj = TF.lmms.5tp$pspline, time = time)
TF.lmms.filtered.5tp <- TF.lmms.filter$filtered
TF.lmms.filtered.5tp.no_model <- TF.lmms.5tp$X %>% dplyr::select(colnames(TF.lmms.filtered.5tp))
TF.lmms.filtered.5tp.no_model.ctrl <- TF.ctr %>% t %>% as.data.frame() %>% `+`(1) %>% log %>%
    dplyr::select(colnames(TF.lmms.filtered.5tp.no_model)) 

# save(genes.lmms.filtered.5tp, genes.lmms.filtered.5tp.no_model, genes.lmms.filtered.5tp.no_model.ctrl,
#      TF.lmms.filtered.5tp, TF.lmms.filtered.5tp.no_model, TF.lmms.filtered.5tp.no_model.ctrl,
#      file = "Genes_TF_filtered_5TP.rda")
load("Genes_TF_filtered_5TP.rda")
```

## metabolie

```{r metabolite_preprocessing, fig.align="center"}
targeted_metabo <- readxl::read_excel(path = "data/PP2015-01039R1_Supplemental_Tables_S2_S9.xlsx", sheet = 5, skip= 3) %>% dplyr::select(Compound, contains("FC")) %>%
    column_to_rownames("Compound") %>% t %>% as.data.frame() %>% .[1:5,]

# FC
target.sample.5tp.fc <- remove.fold.change(X = t(targeted_metabo), cutoff = log(2), hist.title = "SAMPLES -- Metabo -- 5TP FC log(2)") %>% t %>% as.data.frame()

time <- c(2,4,8,24,48)
splines.targeted_metabo.5tp <- lapply(target.sample.5tp.fc, function(x) 
    fit.spline.predict(X =x, spar = 0.2, time = time, time.pred = seq(2,48,by=2))) %>%
    as.data.frame()

rownames(splines.targeted_metabo.5tp) = seq(2, 48, by = 2)
splines.targeted_metabo.5tp %>% scale() %>% as.data.frame() %>% 
    rownames_to_column("time") %>% 
    gather(metabolite, value, - time) %>%
    mutate(time = as.numeric(time)) %>%
    ggplot(aes(time, value, col = metabolite)) + geom_line() +
    theme(legend.position = "none")

#save(splines.targeted_metabo.5tp, file = "targeted_metabo_5TP.rda")
load("targeted_metabo_5TP.rda")
```

# Clustering

```{r timeOmics}
data = list(RNA = genes.lmms.filtered.5tp, TF = TF.lmms.filtered.5tp, metabo = splines.targeted_metabo.5tp)
data <- lapply(data, scale)

block.pls.res <- block.pls(X=data, indY = 1, ncomp = 10, mode = "canonical")
block.ncomp <- getNcomp(block.pls.res, X=data, indY = 1, mode = "canonical")
plot(block.ncomp)

block.pls.res <- block.pls(X=data, indY = 1, ncomp = 2, mode = "canonical")
plotLong(block.pls.res, legend = TRUE, title = "timeOmics clusterin, ncomp = 2")

cluster.info.block.pls.res.5tp <- getCluster(block.pls.res)

#save(cluster.info.block.pls.res.5tp, file = "timeOmics_block_5tp.rda")
load("./timeOmics_block_5tp.rda")
```

```{r timeOmics_res}
cluster.info.block.pls.res.5tp %>% group_by(cluster, block) %>%
    summarise(N=n()) %>%
    spread(block, N) %>%
    column_to_rownames("cluster")
```


# Networks

## GRN
```{r grn}
# sample + control
X1 <- rbind(genes.lmms.filtered.5tp.no_model, genes.lmms.filtered.5tp.no_model.ctrl) %>%
cbind(rbind(TF.lmms.filtered.5tp.no_model, TF.lmms.filtered.5tp.no_model.ctrl))
G <- get_graph(X1)$G

mol_cluster <- cluster.info.block.pls.res.5tp %>% 
    filter(block %in% c("RNA","TF")) %>%
    split(.$cluster) %>% 
    lapply(function(x) pull(x,molecule))

par(mfrow=c(2,2))
timeOmics_first_G <- list()
for(cluster in 1:4){
    # split
    X = X1 %>% as.data.frame %>% dplyr::select(mol_cluster[[cluster]])
    G3 <- get_graph(X)$G
    
    Isolated = which(degree(G3)==0)
    G4 = delete.vertices(G3, Isolated)
    
    timeOmics_first_G[[names(mol_cluster)[cluster]]] <- G3
    
    G4$color <- case_when(names(V(G4)) %in% setdiff(mol_cluster[[cluster]],TF.list) ~ color.mixo(cluster),
                          names(V(G4)) %in%  TF.list~ "red")
    
    plot(G4, vertex.label = NA, vertex.size = 4, vertex.color = G4$color,
         vertex.frame.color = ifelse(names(V(G3)) %in% TF.list, "red", "grey"))
    title(main = paste0("Cluster ", names(mol_cluster)[cluster]))
    legend("bottomleft", legend = c(paste0("V = ", length(V(G4)-sum(G4$color == "red"))), 
                                    paste0("E = ",length(E(G4))),
                                    paste0("Deg-0 = " ,sum(degree(G3) == 0))),
           lty = c(NA,1, NA), 
           pch = c(19,NA, NA), 
           col = c(color.mixo(cluster), "darkgrey", NA))
}

par(mfrow=c(1,1))

#save(G, timeOmics_first_G, file = "GRN.rda")
load("GRN.rda")
```

```{r grn_res}
imap_dfr(timeOmics_first_G, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y)) 
```

## PPIM
```{r ppim}
# ppim collection : http://comp-sysbio.org/ppim/download/PPIcollection.txt
ppim <- read_tsv("data/maize_ppi_collection.txt", col_names = c("P1", "P2", "interact_type", "confident_score", "interactor")) %>%
    mutate(P1 = P1 %>% str_remove("_P..$"), 
           P2 = P2 %>% str_remove("_P..$")) %>%
    filter(P1 != P2)

TF <- read_tsv("data/TF_formatted.txt", col_names = c("NAME", "SYMBOL")) %>%
    mutate(NAME = NAME %>% str_remove("_P..$"))

ppim_high <- ppim %>% filter(confident_score %in% c("high", "high;literature", "literature"))  %>% 
    dplyr::select(P1, P2) %>% unique()
PPIM <- graph_from_data_frame(ppim_high, directed = FALSE)

GRN_PPIM <- list()
for(i in names(timeOmics_first_G)){
    sub <- timeOmics_first_G[[i]]
    GRN_PPIM[[i]] <- plot_grn_ppi_neighbors(sub, PPIM, order = 1, plot.title = paste0("Cluster ",i), plot = FALSE)
}

GRN_PPIM[["all"]] <- plot_grn_ppi_neighbors(G, PPIM, order = 1, plot.title = paste0("All clusters"), plot = TRUE)

#save(GRN_PPIM, file = "GRN_PPIM.rda")
load("GRN_PPIM.rda")
```

## Metabolite
```{r metabolite_kegg, warning=FALSE, message=FALSE}
#source("../analysis/kegg_explore.R")
load("../analysis/kegg_explore_res.rda")
```

```{r metabolite_network, warning=FALSE, message=FALSE, fig.align="center"}
# metabolite name to compound
metabo_w_compound_id_tmp <- read_tsv("data/metabo_kegg_id.tsv.csv")

metabo_w_compound_id <- cluster.info.block.pls.res.5tp %>%
    filter(block == "metabo") %>% mutate(molecule = metabo_w_compound_id_tmp$Compound) %>%
    left_join(metabo_w_compound_id_tmp, by = c("molecule"= "Compound")) %>%
    dplyr::select(-c(contrib.max, contribution))
metabo_nodes <- metabo_w_compound_id$Compound_ID %>% na.omit %>% str_remove_all(" ") %>%
    str_split(";") %>% unlist

all_metabo.igraph <- igraph::graph_from_data_frame(d = reaction_mapformula_df, directed = FALSE)
# add rn -> keggID -> zma: -> gene v3
only_reaction <- reaction_mapformula_df %>% filter(p1 %in% metabo_nodes | p2 %in% metabo_nodes) %>% pull(rn) %>% as.character()
reaction_mapformula_df_filtered <- reaction_mapformula_df %>% filter(rn %in% only_reaction)
all_metabo_of_interest.igraph <- igraph::graph_from_data_frame(reaction_mapformula_df_filtered, directed = FALSE)

# how many from the original 40 ?
metabo_w_compound_id$Compound_ID %>% na.omit %>% str_remove_all(" ") %>% str_split(";") %>% 
    lapply(function(x) x %in% metabo_nodes[metabo_nodes %in% names(V(all_metabo_of_interest.igraph))] %>% any) %>% unlist %>% sum

all_gene_prot_nodes <- lapply(GRN_PPIM, function(x) names(V(x$graph))) %>% unlist
interaction_df <- rn_to_gene %>% filter(rn %in% only_reaction) %>% 
    filter(v3_gene_model %in% all_gene_prot_nodes) %>% right_join(reaction_mapformula_df_filtered) %>%
    na.omit()

# metabo graph
METABO <- lapply(names(timeOmics_first_G), function(x)get_metabo_graph(x, metabo_w_compound_id))
names(METABO) <- names(timeOmics_first_G)

# by cluster
GRN_PPIM_METABO <- lapply(names(timeOmics_first_G), function(clu) {
    add_metabo_layer(GRN = timeOmics_first_G[[clu]], GRN_P = GRN_PPIM[[clu]]$graph, METABO_M = METABO[[clu]], interaction_df, clu)
})

# all
cpd_of_interest <- metabo_w_compound_id %>% pull(Compound_ID) %>% str_split(";") %>% unlist %>% na.omit
metabo.graph.clu <- reaction_mapformula_df_filtered %>% filter(p1 %in% cpd_of_interest | p2 %in% cpd_of_interest) %>%
    graph_from_data_frame(directed = FALSE)
vertex_attr(metabo.graph.clu)$color <- case_when(
    vertex_attr(metabo.graph.clu)$name %in%  cpd_of_interest ~ "purple",
    !(vertex_attr(metabo.graph.clu)$name %in%  cpd_of_interest) ~ "green"
)
tmp <- add_metabo_layer(GRN = G, GRN_P = GRN_PPIM[["all"]]$graph, METABO_M = metabo.graph.clu, interaction_df, "ALL")
names(GRN_PPIM_METABO) <- names(timeOmics_first_G)
GRN_PPIM_METABO[["all"]] <- tmp
# end all

# remove edge attributes
for(clu in names(GRN_PPIM_METABO)){
    tmp <- GRN_PPIM_METABO[[clu]]$graph
    for(attribute in names(edge_attr(tmp))){
        tmp <- delete_edge_attr(tmp, name = attribute)
    }
    GRN_PPIM_METABO[[clu]]$graph <- tmp
    GRN_PPIM_METABO[[clu]]$simplify <- remove.isolated.nodes(tmp, simplify = TRUE)
}
#save(GRN_PPIM_METABO, file = "GRN_PPIM_METABO.rda")
load("GRN_PPIM_METABO.rda")
```

```{r metabolite_network_res}
imap_dfr(GRN_PPIM_METABO, ~get_stats_graph(.x$graph) %>% as.data.frame %>% mutate(cluster = .y)) 
imap_dfr(GRN_PPIM_METABO, ~vertex_attr(.x$graph) %>% as.data.frame %>% mutate(cluster = .y)) %>%
    group_by(color, cluster) %>% summarise(N=n()) %>%
    spread(cluster, N) %>%
    column_to_rownames("color") %>%
    #.[c(1,2),] %>% colSums() %>%
    dplyr::select("1","-1","2","-2","all") %>% .[c(2,3,5,4,1),]
```

# Enrichment ORA

```{r ora, eval = FALSE}
genes_v3v4 <- read_tsv("data/gene_model_xref_v4.txt", skip = 4) %>% dplyr::select(c("v4_gene_model", "v3_gene_model", "Entrez"))

enrich <- list()
enrich_1 <- list()
enrich_2 <- list()
all_query1 <- vector()
all_query2 <- vector()
for(clu in names(GRN_PPIM_METABO)){
    query1 <- vertex_attr(GRN_PPIM_METABO[[clu]]$graph) %>% as.data.frame() %>% filter(color %in% c("lightblue", "orange")) %>% dplyr::select(name) %>%
        left_join(genes_v3v4, by = c("name"="v3_gene_model")) %>% dplyr::select("v4_gene_model") %>% pull
    all_query1 <- c(all_query1, query1)
    enrich_1[[clu]] <- gprofiler2::gost(query = query1, organism = "zmays")
    
    query2 <- vertex_attr(GRN_PPIM_METABO[[clu]]$graph) %>% as.data.frame() %>% filter(color %in% c("lightblue", "orange", "yellow")) %>% dplyr::select(name) %>%
        left_join(genes_v3v4, by = c("name"="v3_gene_model")) %>% dplyr::select("v4_gene_model") %>% pull
    all_query2 <- c(all_query1, query2)
    enrich_2[[clu]] <- gprofiler2::gost(query = query2, organism = "zmays")
    
    enrich[[clu]] <- gprofiler2::gost(query = c(query1, query2), organism = "zmays")
}

goterm_map <- gprofiler2::gconvert(query = na.omit(all_query2), organism = "zmays", target = "GO") 


# filter go term signif
all_enrich <- gprofiler2::gost(query = all_query1,organism = "zmays", significant = FALSE)
signif_go <- all_enrich$result %>% filter(significant == TRUE) %>% pull(term_id) %>% unlist
goterm_map.signif <- goterm_map %>% filter(target %in% signif_go) %>%
    left_join(genes_v3v4, by = c("input"="v4_gene_model"))
goterm_map.v3 <- goterm_map %>% left_join(genes_v3v4, by = c("input"="v4_gene_model"))

# same but extended
all_all_enrich <- gprofiler2::gost(query = all_query2,organism = "zmays", significant = FALSE)
signif_go_all <- all_all_enrich$result %>% filter(significant == TRUE) %>% pull(term_id) %>% unlist
goterm_map_all.signif <- goterm_map %>% filter(target %in% signif_go_all) %>%
    left_join(genes_v3v4, by = c("input"="v4_gene_model"))

interaction_gene_go <- goterm_map_all.signif %>% 
    dplyr::select(c(target, v3_gene_model))

GRN_PPIM_METABO_GO <- lapply(GRN_PPIM_METABO, function(x) add_go_term_layer(x$graph))
#save(GRN_PPIM_METABO_GO, interaction_gene_go, file = "GRN_PPIM_METABO_GO.rda")
load("GRN_PPIM_METABO_GO.rda")
```
```{r}
load("GRN_PPIM_METABO_GO.rda")
```

```{r ora_res}
imap_dfr(GRN_PPIM_METABO_GO, ~get_stats_graph(.x) %>% as.data.frame %>% mutate(cluster = .y)) 
```

```{r ora_res_2}
enrich_res_comp2 <- lapply(GRN_PPIM_METABO, function(x){
    get_enrichment(x$graph)
})

df.comp_2.raw <- imap_dfr(enrich_res_comp2, ~.x$res_raw$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                              dplyr::select(term_id, source, p_value, cluster)) %>% filter(source != "KEGG") %>% mutate(mode = "raw")
df.comp_2.ext <- imap_dfr(enrich_res_comp2, ~.x$res_extended$result %>% mutate(cluster = .y) %>% filter(significant == TRUE) %>%
                              dplyr::select(term_id, source, p_value, cluster)) %>% filter(source != "KEGG") %>% mutate(mode = "extended")
df.comp_2 <- rbind(df.comp_2.raw, df.comp_2.ext) %>% 
    mutate(approach = ifelse(cluster == "all", "all", "by_cluster") %>% factor(level = c("by_cluster", "all"))) %>%
    mutate(mode = factor(mode, levels = c("raw", "extended")))
```

```{r ora_res_export}

```

```{r ora_res_3}
# final stat
df.comp_2 %>% dplyr::select(mode, term_id, source) %>% unique %>% 
    group_by(source, mode) %>%
    summarise(N = n()) %>%
    spread(source, N)

df.comp_2 %>% dplyr::select(mode, term_id, source, cluster) %>%
    filter(mode == "raw") %>% unique %>% 
    group_by(source, cluster) %>%
    summarise(N = n()) %>%
    spread(source, N)

df.comp_2 %>% dplyr::select(mode, term_id, source, cluster) %>%
    filter(mode == "extended") %>% unique %>% 
    group_by(source, cluster) %>%
    summarise(N = n()) %>%
    spread(source, N)

tmp.go_terms <- df.comp_2$term_id %>% map_df(~get_go_info(.x))
df.comp_2 %>% dplyr::select(mode, term_id, source, cluster, p_value) %>%
    filter(mode == "raw") %>% arrange(desc(p_value)) %>%
    left_join(tmp.go_terms, by = c('term_id' = 'name'))
    


# cluster specific and only visible in cluster (no global)
df.comp_2 %>% filter(mode == "raw") %>%
    dplyr::select(term_id, source, cluster, approach) %>%
    group_by(term_id, source) %>%
    summarise(N = n()) %>% filter(N == 1) %>% pull(term_id) -> tmp.unique.termi_id
df.comp_2 %>% filter(mode == "raw") %>% 
    filter(term_id %in% tmp.unique.termi_id) %>%
    left_join(map_dfr(tmp.unique.termi_id, ~get_go_info(.x)), by = c('term_id' = 'name'))


png("./figure/CS2_goterm_enr.png", height =  1500, width = 2000, res = 300)
df.comp_2 %>% mutate(approach = ifelse(approach == "by_cluster", "By_Cluster", "Global")) %>%
    mutate(mode = ifelse(mode == "raw", "Raw", "Extended") %>% factor(levels = c("Raw", "Extended"))) %>%
ggplot(aes(x = -log10(p_value), fill = mode)) +
    geom_histogram() +
    theme_bw() +
    scale_fill_manual(values = c("lightgrey", "black")) +
    theme(legend.position = "none") +
    facet_grid(approach~mode) +
    ylab("Number of GO terms")
dev.off()

png("./figure/CS2_goterm_enr_2.png", height =  1500, width = 2000, res = 300)
df.comp_2 %>%
     mutate(approach = ifelse(approach == "by_cluster", "By_Cluster", "Global")) %>%
    mutate(mode = ifelse(mode == "raw", "Raw", "Extended") %>% factor(levels = c("Raw", "Extended"))) %>%
    dplyr::select(term_id, approach, mode) %>% 
    unique %>%
    group_by(approach, mode) %>%
    summarise(n_go = n()) %>%
    ggplot(aes(approach, y = n_go, fill = mode)) + 
    geom_bar(stat = "identity", position = "dodge", width = 0.3) +
    geom_text(aes(label = n_go), vjust=-0.5, color="black",position = position_dodge(0.3)) +
    theme_bw() + xlab("Clustering approach") + ylab("Number of distinct GO terms") + 
    scale_fill_manual(values = c("lightgrey", "black")) +
    labs(fill = "Omic type")
dev.off()

set.count.raw <-  df.comp_2 %>% filter(mode == "raw", cluster != "all") %>% split(.$cluster) %>% lapply(function(x) pull(x, term_id))
names(set.count.raw) <- paste0("Cluster_", 1:4)
set.count.raw <- make_comb_mat(set.count.raw, min_set_size = 0)

set.count.ext <-  df.comp_2 %>% filter(mode == "extended", cluster != "all") %>% split(.$cluster) %>% lapply(function(x) pull(x, term_id))  
names(set.count.ext) <- paste0("Cluster_", 1:4)
set.count.ext <- make_comb_mat(set.count.ext, min_set_size = 0)

set.count.raw <- set.count.raw[union(comb_name(set.count.raw), comb_name(set.count.ext))]
set.count.ext <- set.count.ext[union(comb_name(set.count.raw), comb_name(set.count.ext))]

top_ha = HeatmapAnnotation(
    "Raw" = anno_barplot(comb_size(set.count.raw), gp = gpar(fill = "lightgrey"), height = unit(2, "cm")),
    "Extended" = anno_barplot(comb_size(set.count.ext), gp = gpar(fill = "black"), height = unit(2, "cm")),
    annotation_name_side = "left", annotation_name_rot = 0)

png("./figure/CS2_goterm_enr_3.png", height =  1300, width = 4000, res = 300)
UpSet(set.count.ext, top_annotation = top_ha,heigh = unit(5, "cm"), row_title = "Clusters")
dev.off()

```

short graph for RWR function prediction
```{r ora_rwr_graph}
load("data/GO_graphs.rda")
add_go_term_annot <- function(graph, go.graph){
    interaction.graph <- goterm_map %>%
        left_join(genes_v3v4, by = c("input"="v4_gene_model")) %>%
        dplyr::select(v3_gene_model, target) %>%
        na.omit() %>%
        filter(v3_gene_model %in% names(V(graph)), 
               target %in% V(go.graph)$name) %>%
        igraph::graph.data.frame(directed = FALSE) 
    
    graph_tmp <- igraph::union(graph, interaction.graph)
    full_graph <- igraph::union(graph_tmp, as.undirected(go.graph))
    vertex_attr(full_graph) <- vertex_attr(full_graph) %>% as.data.frame(stringsAsFactors = FALSE) %>% 
        mutate(type = ifelse(is.na(type), "Gene", type)) %>%
        as.list()
    return(full_graph)
}
vertex_attr(GOCC_graph)$type <- rep("GO:CC", vcount(GOCC_graph))
vertex_attr(GOBP_graph)$type <- rep("GO:BP", vcount(GOBP_graph))
vertex_attr(GOMF_graph)$type <- rep("GO:MF", vcount(GOMF_graph))

FINAL_GOBP <- add_go_term_annot(graph = GRN_PPIM$all$graph, go.graph = as.undirected(GOBP_graph))
FINAL_GOCC <- add_go_term_annot(graph = GRN_PPIM$all$graph, go.graph = as.undirected(GOCC_graph))
FINAL_GOMF <- add_go_term_annot(graph = GRN_PPIM$all$graph, go.graph = as.undirected(GOMF_graph))

FINAL_GO_ANNOT <- list("BP" = FINAL_GOBP,
                       "CC" = FINAL_GOCC,
                       "MF" = FINAL_GOMF)

FINAL_GOBP_short <- add_go_term_annot(graph = G, go.graph = as.undirected(GOBP_graph))
FINAL_GOCC_short <- add_go_term_annot(graph = G, go.graph = as.undirected(GOCC_graph))
FINAL_GOMF_short <- add_go_term_annot(graph = G, go.graph = as.undirected(GOMF_graph))

FINAL_GO_ANNOT_short <- list("BP" = FINAL_GOBP_short,
                       "CC" = FINAL_GOCC_short,
                       "MF" = FINAL_GOMF_short)
```

```{r final_network}
FINAL <- imap(GRN_PPIM_METABO_GO, ~reformate_graphs(.x, .y))
imap_dfr(FINAL, ~vertex_attr(.x) %>% as.data.frame %>% mutate(cluster = .y)) %>%
     group_by(color, cluster) %>% summarise(N=n()) %>%
     spread(cluster, N) %>%
     column_to_rownames("color") %>%
     #.[c(1,2),] %>% colSums() %>%
     dplyr::select("1","-1","2","-2","all")
```

# Random Walk

## Mechanisms
```{r RWR_meca_1}
list_of_go <- df.comp_2 %>% filter(mode == "raw") %>% pull(term_id) %>% unique
set.seed(1)
RWR_meca_res <- parallel::mclapply(FINAL, function(graph) RWR_with_go(graph, list_of_go, k = 25), mc.cores = 4) 
#save(RWR_meca_res, file = "RWR_meca_res.rda") 
load("RWR_meca_res.rda")
```


```{r RWR_meca_res}
va.all <- FINAL$all %>% vertex_attr()
va.all <- imap_dfr(FINAL, ~(vertex_attr(.x) %>% mutate(CLUSTER = .y))) %>% dplyr::select(type, name, color, molecule, size, lab) %>% unique
stat_rwr_comp2 <- imap_dfr(RWR_meca_res, ~stat_table(.x, va.all) %>% mutate(cluster=.y)) 
stat_rwr_comp2 %>% filter(metabo_targeted >0) 
```

```{r}
RWR_meca_res_tmp <-  imap_dfr(RWR_meca_res, ~{
    lapply(names(.x), function(i)
        vertex_attr(RWR_meca_res[[.y]][[i]]) %>% mutate(cluster =.y, Seed = i))})
```

Case of Phenylpropanoid
```{r}
phe <- RWR_meca_res$all$`GO:0009698` %>% vertex_attr()  %>% dplyr::select(-lab) %>%
    left_join(rbind.info) 

phe_reac <- reaction_mapformula_df %>% filter(p1 %in% phe$name | p2 %in% phe$name) %>% pull(rn) %>% as.character() %>% unique
rn_to_gene %>% filter(v3_gene_model %in% phe$name & rn %in% phe_reac) %>% left_join(rbind.info, by = c("v3_gene_model"="name"))
reaction_mapformula_df %>% filter(p1 %in% c("C00423", "C00079") & p2 %in% c("", "C00079"))
reaction_mapformula_df %>% filter(p1 %in% c("C00082", "C00811") & p2 %in% c("C00082", "C00811"))


plot(RWR_meca_res$all$`GO:0009698`)
tmp <- make_ego_graph(RWR_meca_res$all$`GO:0009698`, order = 1, nodes = phe %>% filter(molecule == "metabo") %>% pull(name))
tmp <- make_ego_graph(RWR_meca_res$all$`GO:0009698`, order = 1, nodes = phe %>% filter(color == "yellow") %>% pull(name))
tmp <- make_ego_graph(RWR_meca_res$all$`GO:0009698`, order = 1, nodes = phe %>% filter(name == "GRMZM2G074604") %>% pull(name))
lapply(tmp, plot)

# cluster 2
phe <- RWR_meca_res$`-1`$`GO:0009698` %>% vertex_attr()  %>% dplyr::select(-lab) %>%
    left_join(rbind.info) 
phe %>% filter(molecule == "metabo", color == "purple")

phe_reac <- reaction_mapformula_df %>% filter(p1 %in% phe$name | p2 %in% phe$name) %>% pull(rn) %>% as.character() %>% unique
rn_to_gene %>% filter(v3_gene_model %in% phe$name & rn %in% phe_reac) %>% left_join(rbind.info, by = c("v3_gene_model"="name"))

# cluster 4
phe <- RWR_meca_res$`-2`$`GO:0009698` %>% vertex_attr()  %>% dplyr::select(-lab) %>%
    left_join(rbind.info) 
phe %>% filter(molecule == "metabo", color == "purple")

phe_reac <- reaction_mapformula_df %>% filter(p1 %in% phe$name | p2 %in% phe$name) %>% pull(rn) %>% as.character() %>% unique
rn_to_gene %>% filter(v3_gene_model %in% phe$name & rn %in% phe_reac) %>% left_join(rbind.info, by = c("v3_gene_model"="name"))
```



## Function Prediction
```{r RWR_pred}
gene_name <- (map_dfr(FINAL, ~vertex_attr(.x)) %>% filter(color %in% c("lightblue", "orange")) %>% pull(name) %>% unique)
# 
unkown_seeds <- gene_name[!(gene_name %in% (goterm_map %>% left_join(genes_v3v4, by = c("input"="v4_gene_model")) %>% pull(v3_gene_model) %>%  unique))]


# 1. monoplex
res <- as.list(unkown_seeds)
names(res) = unkown_seeds

RES_aggregation <- lapply(FINAL_GO_ANNOT, function(graph){
    lapply(res, function(seed){
        find_annotation(graph = graph, seed = seed)
    })
})
RES_aggregation_short <- lapply(FINAL_GO_ANNOT_short, function(graph){
    lapply(res, function(seed){
        find_annotation(graph = graph, seed = seed)
    })
})
```

```{r RWR_pred_res}
#save(RES_aggregation, RES_aggregation_short, file = "RWR_pred_monoplex.rda") 
load("RWR_pred_monoplex.rda")

tmp.aggregation <- imap_dfr(RES_aggregation$BP, ~annot_RWR_res(.x) %>% mutate(type = "BP", seed = .y)) %>% na.omit()  %>% rbind(
imap_dfr(RES_aggregation$CC, ~annot_RWR_res(.x) %>% mutate(type = "CC", seed = .y)) %>% na.omit()) %>% rbind(
imap_dfr(RES_aggregation$MF, ~annot_RWR_res(.x) %>% mutate(type = "MF", seed = .y)) %>% na.omit()) %>% 
    left_join(map_dfr(.$NodeNames %>% unique, ~get_go_info(.x)), by = c("NodeNames"="name"))

write.csv(tmp.aggregation, "./CS2_RWR_annotation.csv")
```

```{r}
tmp.aggregation$seed %>% unique %>% length()
tmp.aggregation %>% dplyr::select(NodeNames, source) %>% unique

tmp.aggregation %>% filter(type == "BP") %>%
    group_by(NodeNames, type, description) %>%
    summarise(Min = min(position), Max = max(position))

tmp.aggregation %>% filter(type == "BP") %>% dplyr::select(NodeNames, description) %>% unique
tmp.aggregation %>% filter(type == "CC") %>% dplyr::select(NodeNames, description) %>% unique
tmp.aggregation %>% filter(type == "MF") %>% dplyr::select(NodeNames, description) %>% unique
```


## Cluster Annotation

```{r RWR_cluster}
load("timeOmics_block_5tp.rda")
cluster.info <- cluster.info.block.pls.res.5tp 
SEEDS <- cluster.info %>% filter(block %in% c("RNA", "TF")) %>%
    filter(molecule %in% V(FINAL$all)$name) %>%
    pull(molecule)

RWR_res <- as.list(SEEDS)
names(RWR_res) = SEEDS
for(i in SEEDS){
    print(i)
    #res[[i]] <- find_annotation(FINAL_GO_ANNOT$BP, i)
    RWR_res[[i]] <- in_between(FINAL$all, i, k = 10)
}
#save(RWR_res, file = "RWR_cluster.rda") 
```

```{r RWR_cluster_res}
load(file = "RWR_cluster.rda")
va.all <- FINAL$all %>% vertex_attr %>% as.data.frame()
res_between_intersection <- imap(RWR_res, ~detect_intersection(.x, seed_name = .y, va.all))
res_between_intersection %>% lapply(is.null) %>% unlist %>% table
res_between_intersection_with_go <-  res_between_intersection[res_between_intersection %>% lapply(nrow) %>% unlist %>% subset(.>0) %>% names] %>%
    imap_dfr(~{.x %>% mutate(seed = .y)}) %>% dplyr::select(seed, name, description)

res_between_intersection_with_go$seed %>% unique %>% length

res_between_intersection_with_go %>% filter(description %>% str_detect("BP")) %>% group_by(description) %>% summarise(N=n()) %>% arrange(desc(N))
res_between_intersection_with_go %>% filter(description %>% str_detect("CC")) %>% group_by(description) %>% summarise(N=n()) %>% arrange(desc(N))
res_between_intersection_with_go %>% filter(description %>% str_detect("MF")) %>% group_by(description) %>% summarise(N=n()) %>% arrange(desc(N))


#toxin activity (MF)
res_between_intersection_with_go %>% filter(seed %in% (res_between_intersection_with_go %>% filter(description == "toxin activity (MF)") %>% pull(seed)))
res_between_intersection_with_go %>% filter(seed %in% (res_between_intersection_with_go %>% filter(description == "defense response to bacterium (BP)") %>% pull(seed)))

goterm_map.v3 %>% filter(v3_gene_model %in% "GRMZM2G466298") %>% filter(target %in% "GO:0042742")

#"toxin activity (MF)"
toxin.tmp <- res_between_intersection_with_go %>% filter(description == "toxin activity (MF)") %>% pull(seed) 
res_between_intersection_with_go %>% filter(seed %in% toxin.tmp) %>% left_join(cluster.info, by = c("name"="molecule"))


# "lignin biosynthetic process (BP)"    
lignin.tmp <- res_between_intersection_with_go %>% filter(description == "lignin biosynthetic process (BP)") %>% pull(seed) 
res_between_intersection_with_go %>% filter(seed %in% lignin.tmp[2]) %>% left_join(cluster.info, by = c("name"="molecule"))

    
# "defense response to bacterium (BP)"  
defence.tmp <- res_between_intersection_with_go %>% filter(description == "defense response to bacterium (BP)") %>% pull(seed) 
res_between_intersection_with_go %>% filter(seed %in% defence.tmp[2]) %>% left_join(cluster.info, by = c("name"="molecule"))

RWR_res$GRMZM5G814904

res_between_intersection_with_go %>% left_join(cluster.info, by = c("name"="molecule")) %>% filter(!is.na(cluster)) %>%
    group_by(seed) %>% summarise(N = n()) %>%
    arrange(desc(N))

res_between_intersection_with_go %>% left_join(cluster.info, by = c("name"="molecule")) %>% filter(!is.na(cluster)) %>%
    dplyr::select(seed, cluster) %>% unique %>%
    group_by(seed) %>% summarise(N = n()) %>%
    arrange(desc(N))

plot.graph.tmp <- RWR_res[["AC209374.4_FG002"]] 
set.seed(2)
l <- layout_nicely(plot.graph.tmp)
l <- norm_coords(l, ymin=-1, ymax=1, xmin=-1, xmax=1)
seed.plot = "AC209374.4_FG002"

vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>% as.data.frame() %>% left_join(va.all) %>% 
    dplyr::select(-cluster) %>% left_join(cluster.info, by = c("name"="molecule")) 

vertex_attr(plot.graph.tmp)<- vertex_attr(plot.graph.tmp) %>%
    mutate(color = ifelse(type == "prot_ego", "orange", color),
           color = ifelse(type == "gene_prot", "lightblue", color),
           color = ifelse(name == seed.plot, "red", color), 
           color = ifelse(!is.na(cluster), color, "lightgrey"), 
           #frame.color = ifelse(type %in% c("Prot.ego", "Metabolite"), "red", "darkgrey"),
           frame.color = case_when(
               cluster == 1 ~ "purple",
               cluster == 2 ~ "darkgreen",
               cluster == -1 ~ "blue",
               cluster == -2 ~ "orange",
               TRUE ~ "grey"
           ),
           frame.width = 10,
           size = ifelse(type %in% c("Prot.ego", "Metabolite"), 5,6), 
           size = ifelse(name == seed.plot, 8, size))

png("./figure/cs2_rwr_cluster.png", height =  3000, width = 3500, res = 300)
plot(plot.graph.tmp, layout=l)
legend("topleft", 
       legend = c("SEED", "Genes", "Ext. neighbours"),
       col = c("red", "lightblue", "lightgrey"),
       pch = c(19, 19, 19, 19, 19, 1),
       pt.cex = c(1.5, 1, 1, 1, 1, 1.5), 
       cex = 1.3,
       box.col="white"
)

legend("bottomright", 
       legend = paste0("Cluster ", 1:4),
       col = c("purple", "blue", "darkgreen", "orange"),
       pch = c(1),
       cex = 1.3,
       box.col="white"
)
title("AC209374.4_FG002\n(mecs2 - methyl erythritol cyclodiphosphate synthase2)")
dev.off()


tmp.no.model <- genes.lmms.filtered.5tp.no_model %>% rownames_to_column("sample") %>% 
                  mutate(time = sample %>% str_remove("sample_") %>% str_remove("h_.*")) %>%
                  gather(name, value, -c(time, sample)) %>%
    filter(name %in% vertex_attr(plot.graph.tmp)$name) %>%
    mutate(time = as.numeric(time)) %>%
    left_join(vertex_attr(plot.graph.tmp)) %>% dplyr::select(time, name, value, cluster) %>%
    mutate(cluster = case_when(
        cluster == 1 ~ "Cluster 1",
        cluster == -1 ~ "Cluster 2",
        cluster == 2 ~ "Cluster 3",
        cluster == -2 ~ "Cluster 4",
    )) %>%
    arrange(cluster) 
order.name <- tmp.no.model$name %>% unique

tmp.no.model<- tmp.no.model %>% mutate(name = factor(name, levels = order.name))
# long clustering
tmp.model <- genes.lmms.filtered.5tp %>% rownames_to_column("time") %>%
    gather(name, value, -time) %>%
    left_join(vertex_attr(plot.graph.tmp)) %>%
    filter(!is.na(cluster)) %>%
    dplyr::select(time, name, value, cluster) %>%
    mutate(time = as.numeric(time)) %>%
        mutate(cluster = case_when(
        cluster == 1 ~ "Cluster 1",
        cluster == -1 ~ "Cluster 2",
        cluster == 2 ~ "Cluster 3",
        cluster == -2 ~ "Cluster 4",
    )) %>%
    mutate(name = factor(name, levels = order.name))

png("./figure/cs2_rwr_cluster_dyn.png", height =  2500, width = 2000, res = 300)
ggplot(tmp.model, aes(x=time, y=value, group = name, col = cluster)) + geom_line() +
    geom_point(data = tmp.no.model) +
    #facet_wrap(name~., dir = "v", ncol = 1, scales = "free") +
    facet_grid(name~., scales = "free") +

    theme_bw() +
    scale_color_manual(values = c("purple", "blue", "darkgreen", "orange")) +
    labs(x = "Time", y = "Expression value", col = "Cluster") +
    theme(legend.position = "top")
dev.off()
    
```

```{r}
openxlsx::write.xlsx(x = list("mechanism" = RWR_meca_res_tmp, 
                              "prediction" = tmp.aggregation,
                              "cluster" = res_between_intersection_with_go),
                     file = "./table_maize_rwr.xlsx")
```

